---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app audiobookbay
  namespace: flux-system
spec:
  path: ./clusters/main/apps/media/audiobookbay/app
  targetNamespace: personal
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: external-secrets-stores
    - name: rook-ceph-cluster
    - name: democratic-csi-nfs
  prune: true
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
