---
clusterName: &cluster main

endpoint: https://192.168.10.200:6443

talosVersion: v1.9.1
kubernetesVersion: v1.32.0

clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.245.0.0/16

additionalApiServerCertSans: &sans
  - 127.0.0.1
  - 192.168.10.200
  - ::1

additionalMachineCertSans: *sans

cniConfig:
  name: none

nodes:
  - hostname: shiva
    ipAddress: 192.168.10.10
    controlPlane: true
    installDiskSelector:
      serial: 241047FE4737 # CT500T500SSD8 500GB
    talosImageURL: factory.talos.dev/installer/2429a38dd7dd15e11e25b676ce491a89680a72a6fadfa1586e6ec629ae03de8b
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: 58:47:ca:78:ea:26
          driver: i40e
        dhcp: true
        vip:
          ip: 192.168.10.200
        # vlans:
        #   - vlanId: 10
        #     dhcp: false
        #     # addresses:
        #     #   - 192.168.10.10/24
        #     mtu: 1500
        #     routes:
        #       - network: 0.0.0.0/0
        #         gateway: 192.168.10.1
        #     vip:
        #       ip: 192.168.10.200
        #   - vlanId: 20
        #     dhcp: false
        #     # addresses:
        #     #   - 192.168.20.5/24
        #     mtu: 1500
      - deviceSelector:
          busPath: 0-1.0 # ifrit
        dhcp: false
        mtu: 65520
        addresses:
          - 169.254.255.10/32
        routes:
          - network: 169.254.255.11/32
            metric: 2048
      - deviceSelector:
          busPath: 1-1.0 # ramuh
        dhcp: false
        mtu: 65520
        addresses:
          - 169.254.255.10/32
        routes:
          - network: 169.254.255.12/32
            metric: 2048

  - hostname: ifrit
    ipAddress: 192.168.10.11
    controlPlane: true
    installDiskSelector:
      model: "WD_BLACK SN850X 1000GB"
    talosImageURL: factory.talos.dev/installer/2429a38dd7dd15e11e25b676ce491a89680a72a6fadfa1586e6ec629ae03de8b
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: 58:47:ca:7a:52:28
          driver: i40e
        dhcp: true
        vip:
          ip: 192.168.10.200
        # vlans:
        #   - vlanId: 10
        #     dhcp: false
        #     addresses:
        #       - 192.168.10.11/24
        #     mtu: 1500
        #     routes:
        #       - network: 0.0.0.0/0
        #         gateway: 192.168.10.1
        #     vip:
        #       ip: 192.168.10.200
        #   - vlanId: 20
        #     dhcp: false
        #     # addresses:
        #     #   - 192.168.20.6/24
        #     mtu: 1500
      - deviceSelector:
          busPath: 0-1.0 # shiva
        dhcp: false
        mtu: 65520
        addresses:
          - 169.254.255.11/32
        routes:
          - network: 169.254.255.10/32
            metric: 2048
      - deviceSelector:
          busPath: 1-1.0 # ramuh
        dhcp: false
        mtu: 65520
        addresses:
          - 169.254.255.11/32
        routes:
          - network: 169.254.255.12/32
            metric: 2048

  - hostname: ramuh
    ipAddress: 192.168.10.12
    controlPlane: true
    installDiskSelector:
      model: "WD_BLACK SN850X 1000GB"
    talosImageURL: factory.talos.dev/installer/2429a38dd7dd15e11e25b676ce491a89680a72a6fadfa1586e6ec629ae03de8b
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: 58:47:ca:79:7a:50
          driver: i40e
        dhcp: true
        vip:
          ip: 192.168.10.200
        # vlans:
        #   - vlanId: 10
        #     dhcp: false
        #     addresses:
        #       - 192.168.10.12/24
        #     mtu: 1500
        #     routes:
        #       - network: 0.0.0.0/0
        #         gateway: 192.168.10.1
        #     vip:
        #       ip: 192.168.10.200
        #   - vlanId: 20
        #     dhcp: false
        #     # addresses:
        #     #   - 192.168.20.7/24
        #     mtu: 1500
      - deviceSelector:
          busPath: 0-1.0 # ifrit
        dhcp: false
        mtu: 65520
        addresses:
          - 169.254.255.12/32
        routes:
          - network: 169.254.255.11/32
            metric: 2048
      - deviceSelector:
          busPath: 1-1.0 # shiva
        dhcp: false
        mtu: 65520
        addresses:
          - 169.254.255.12/32
        routes:
          - network: 169.254.255.10/32
            metric: 2048

controlPlane:
  nodeLabels:
    topology.kubernetes.io/region: *cluster

  schematic:
    customization:
      extraKernelArgs:
        - talos.platform=metal
        - reboot=k
        - mitigations=off
        - net.ifnames=0
        - apparmor=0
        - init_on_alloc=0
        - init_on_free=0
        - intel_iommu=on
        - iommu=pt
        - security=none
      systemExtensions:
        officialExtensions:
          - siderolabs/binfmt-misc
          - siderolabs/i915
          - siderolabs/intel-ucode
          - siderolabs/iscsi-tools
          - siderolabs/mei
          - siderolabs/realtek-firmware
          - siderolabs/thunderbolt
          - siderolabs/util-linux-tools
          - siderolabs/v4l-uvc-drivers

  patches:
    # System Configuration
    - |-
      machine:
        time:
          disabled: false
          servers:
            - time.cloudflare.com
    - |-
      machine:
        sysctls:
          fs.inotify.max_user_watches: 1048576   # Watchdog
          fs.inotify.max_user_instances: 8192    # Watchdog
          vm.nr_hugepages: 1024                  # ISCI
    - |-
      machine:
        kernel:
          modules:
            - name: nbd
            - name: thunderbolt
            - name: thunderbolt_net
    - |-
      machine:
        udev:
          rules:
            - ACTION=="add", SUBSYSTEM=="thunderbolt", ATTR{authorized}=="0", ATTR{authorized}="1"
            - SUBSYSTEM=="drm", KERNEL=="renderD*", GROUP="44", MODE="0660"
    - |
      machine:
        files:
          - op: overwrite
            path: /etc/nfsmount.conf
            permissions: 0o644
            content: |
              [ NFSMount_Global_Options ]
              nfsvers=4.1
              hard=True
              nconnect=16
              noatime=True

    # Container Runtime Configuration
    - |-
      machine:
        files:
          - op: create
            path: /etc/cri/conf.d/20-customization.part
            content: |-
              [plugins."io.containerd.cri.v1.images"]
                discard_unpacked_layers = false

    # Networking Configuration
    - |-
      machine:
        features:
          hostDNS:
            enabled: true
            resolveMemberNames: true
            forwardKubeDNSToHost: false
    - |-
      cluster:
        discovery:
          enabled: true
          registries:
            kubernetes:
              disabled: true
            service:
              disabled: false
    - |-
      machine:
        network:
          disableSearchDomain: true
    - |-
      machine:
        network:
          nameservers:
            - 192.168.10.1

    # Kubernetes Configuration
    - |-
      machine:
        kubelet:
          extraArgs:
            rotate-server-certificates: false
          extraMounts:
            - destination: /var/openebs/local
              type: bind
              source: /var/openebs/local
              options:
                - rbind
                - rshared
                - rw
          nodeIP:
            validSubnets:
              - 192.168.10.0/24
    - |-
      machine:
        features:
          kubePrism:
            enabled: true
            port: 7445
    - |-
      cluster:
        allowSchedulingOnControlPlanes: true
        apiServer:
          extraArgs:
            enable-aggregator-routing: true
            feature-gates: AuthorizeNodeWithSelectors=false
        controllerManager:
          extraArgs:
            bind-address: 0.0.0.0
        coreDNS:
          disabled: true
        etcd:
          extraArgs:
            listen-metrics-urls: http://0.0.0.0:2381
          advertisedSubnets:
            - 192.168.10.0/24
        proxy:
          disabled: true
        scheduler:
          extraArgs:
            bind-address: 0.0.0.0
          config:
            apiVersion: kubescheduler.config.k8s.io/v1
            kind: KubeSchedulerConfiguration
            profiles:
              - schedulerName: default-scheduler
                plugins:
                  score:
                    disabled:
                      - name: ImageLocality
                pluginConfig:
                  - name: PodTopologySpread
                    args:
                      defaultingType: List
                      defaultConstraints:
                        - maxSkew: 1
                          topologyKey: kubernetes.io/hostname
                          whenUnsatisfiable: ScheduleAnyway

    # Security Configuration
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles:
              - os:admin
            allowedKubernetesNamespaces:
              - system-upgrade
              - kube-system
    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl
