---
clusterName: &cluster main
endpoint: https://192.168.10.200:6443
talosVersion: v1.8.3
kubernetesVersion: v1.31.3

clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.245.0.0/16

additionalApiServerCertSans: &sans
  - 127.0.0.1
  - 192.168.10.200
  - ::1

additionalMachineCertSans: *sans

cniConfig:
  name: none

nodes:
  - hostname: shiva
    ipAddress: 192.168.10.10
    controlPlane: true
    installDisk: /dev/nvme0n1
    talosImageURL: factory.talos.dev/installer/cfb759694adabf15484f8318005c7417c4a8051816195b26e057fa3930a07500
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: 58:47:ca:78:ea:26
          driver: i40e
        dhcp: false
        vlans:
          - vlanId: 10
            addresses:
              - 192.168.10.10/24
            mtu: 1500
            routes:
              - network: 0.0.0.0/0
                gateway: 192.168.10.1
            vip:
              ip: 192.168.10.200
          - vlanId: 20
            addresses:
              - 192.168.20.5/24
            mtu: 1500
      - deviceSelector:
          busPath: 0-1.0 # ifrit
        dhcp: false
        mtu: 65520
        addresses:
          - 169.254.255.10/32
        routes:
          - network: 169.254.255.11/32
            metric: 2048

  - hostname: ifrit
    ipAddress: 192.168.10.11
    controlPlane: true
    installDisk: /dev/nvme0n1
    talosImageURL: factory.talos.dev/installer/cfb759694adabf15484f8318005c7417c4a8051816195b26e057fa3930a07500
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: 58:47:ca:7a:52:28
          driver: i40e
        dhcp: false
        vlans:
          - vlanId: 10
            addresses:
              - 192.168.10.11/24
            mtu: 1500
            routes:
              - network: 0.0.0.0/0
                gateway: 192.168.10.1
            vip:
              ip: 192.168.10.200
          - vlanId: 20
            addresses:
              - 192.168.20.6/24
            mtu: 1500
      - deviceSelector:
          busPath: 0-1.0 # shiva
        dhcp: false
        mtu: 65520
        addresses:
          - 169.254.255.11/32
        routes:
          - network: 169.254.255.10/32
            metric: 2048

controlPlane:
  nodeLabels:
    topology.kubernetes.io/region: *cluster
  schematic:
    customization:
      extraKernelArgs:
        - talos.platform=metal
        - reboot=k
        - mitigations=off
        - net.ifnames=0
      systemExtensions:
        officialExtensions:
          - siderolabs/binfmt-misc
          - siderolabs/i915-ucode
          - siderolabs/intel-ucode
          - siderolabs/mei
          - siderolabs/realtek-firmware
          - siderolabs/thunderbolt
          - siderolabs/util-linux-tools
          - siderolabs/v4l-uvc-drivers
          - siderolabs/iscsi-tools

  patches:
    # System Configuration
    - |-
      machine:
        time:
          disabled: false
          servers:
            - time.cloudflare.com
    - |-
      machine:
        sysctls:
          fs.inotify.max_user_watches: 1048576   # Watchdog
          fs.inotify.max_user_instances: 8192    # Watchdog
          fs.inotify.max_queued_events: 65536
          net.core.rmem_max: 67108864            # 10Gb/s | Cloudflared / QUIC
          net.core.wmem_max: 67108864            # 10Gb/s | Cloudflared / QUIC
          vm.nr_hugepages: 1024                  # ISCI
    - |-
      machine:
        kernel:
          modules:
            - name: nbd
            - name: thunderbolt
            - name: thunderbolt_net
    - |-
      machine:
        udev:
          rules:
            - ACTION=="add", SUBSYSTEM=="thunderbolt", ATTR{authorized}=="0", ATTR{authorized}="1"
            - SUBSYSTEM=="drm", KERNEL=="renderD*", GROUP="44", MODE="0660"

    # Container Runtime Configuration
    - |-
      machine:
        files:
          - op: create
            path: /etc/cri/conf.d/20-customization.part
            content: |-
              [plugins."io.containerd.cri.v1.images"]
                discard_unpacked_layers = false

    # Networking Configuration
    - |-
      machine:
        features:
          hostDNS:
            enabled: true
            resolveMemberNames: true
            forwardKubeDNSToHost: false
    - |-
      cluster:
        discovery:
          enabled: true
          registries:
            kubernetes:
              disabled: false
            service:
              disabled: false
    - |-
      machine:
        network:
          disableSearchDomain: true
    - |-
      machine:
        network:
          nameservers:
            - 192.168.10.1

    # Kubernetes Configuration
    - |-
      machine:
        kubelet:
          extraArgs:
            rotate-server-certificates: false
          extraMounts:
            - destination: /var/openebs/local
              type: bind
              source: /var/openebs/local
              options:
                - rbind
                - rshared
                - rw
          nodeIP:
            validSubnets:
              - 192.168.10.0/24
    - |-
      machine:
        features:
          kubePrism:
            enabled: true
            port: 7445
    - |-
      cluster:
        allowSchedulingOnControlPlanes: true
        apiServer:
          extraArgs:
            enable-aggregator-routing: true
            feature-gates: AuthorizeNodeWithSelectors=false
        controllerManager:
          extraArgs:
            bind-address: 0.0.0.0
        coreDNS:
          disabled: true
        etcd:
          extraArgs:
            listen-metrics-urls: http://0.0.0.0:2381
          advertisedSubnets:
            - 192.168.10.0/24
        proxy:
          disabled: true
        scheduler:
          extraArgs:
            bind-address: 0.0.0.0
          config:
            apiVersion: kubescheduler.config.k8s.io/v1
            kind: KubeSchedulerConfiguration
            profiles:
              - schedulerName: default-scheduler
                pluginConfig:
                  - name: PodTopologySpread
                    args:
                      defaultingType: List
                      defaultConstraints:
                        - maxSkew: 1
                          topologyKey: kubernetes.io/hostname
                          whenUnsatisfiable: ScheduleAnyway

    # Security Configuration
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles:
              - os:admin
            allowedKubernetesNamespaces:
              - system-upgrade
    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl
