---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./release.yaml
  - ./pvc.yaml
configMapGenerator:
  - name: mosquitto-configmap
    files:
      - ./resources/mosquitto.conf
generatorOptions:
  disableNameSuffixHash: true
