---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
  - repository.yaml
configMapGenerator:
  - name: flux-operator-values
    files:
      - resources/values.yaml
configurations:
  - resources/kustomizeconfig.yaml
