---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: lb-pool
spec:
  allowFirstLastIPs: "No"
  blocks:
    - cidr: ${NET_SERVICES_CIDR}
      excludeIPs:
        - 192.168.20.1 # Exclude the gateway IP
