---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: control-plane-pool
spec:
  allowFirstLastIPs: "No"
  blocks:
    - cidr: 192.168.10.200
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: services-pool
spec:
  allowFirstLastIPs: "No"
  blocks:
    - start: "192.168.20.10"
      stop: "192.168.20.254"
