---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumloadbalancerippool_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: lb-pool
spec:
  allowFirstLastIPs: "No"
  blocks:
    - cidr: 192.168.20.0/24
    - cidr: ::ffff:192.168.20.0/112  # IPv4-mapped IPv6
    # - start: 192.168.20.10
    #   stop: 192.168.20.254

