---
apiVersion: v1
kind: Service
metadata:
  name: kube-vip
  annotations:
    io.cilium/lb-ipam-ips: "192.168.10.200"
    io.cilium/lb-ipam-pool: "control-plane-pool"  # Specify which pool to use
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    k8s-app: kube-apiserver
    tier: control-plane
  ports:
    - name: https
      port: 6443
      protocol: TCP
      targetPort: 6443
