---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-cloudflare
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.15.1
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app
    image: # TODO: https://github.com/kubernetes-sigs/external-dns/pull/4943
      repository: ghcr.io/buroa/external-dns
      tag: 631b84da
    provider: cloudflare
    env:
      - name: &name CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: &secret external-dns-cloudflare-secret
            key: *name
      - name: &name CF_ZONE_ID
        valueFrom:
          secretKeyRef:
            name: *secret
            key: *name
    extraArgs:
      - --annotation-filter=external-dns.alpha.kubernetes.io/target
      - --cloudflare-proxied
      - --ignore-ingress-tls-spec
      - --ingress-class=external
      - --zone-id-filter=$(CF_ZONE_ID)
      - --cloudflare-dns-records-per-page=1000
    policy: sync
    sources:
      - ingress
    txtOwnerId: main
    txtPrefix: k8s.
    domainFilters:
      - omux.io
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
