apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-machine-learning
spec:
  template:
    spec:
      containers:
        - name: machine-learning
          env:
            - name: MPLCONFIGDIR
              value: "/tmp/matplotlib"
          volumeMounts:
            - name: matplotlib-cache
              mountPath: "/tmp/matplotlib"
      volumes:
        - name: matplotlib-cache
          emptyDir: {}
