---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app chartdb
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      chartdb:
        containers:
          app:
            image:
              repository: ghcr.io/kyteproject/chartdb
              tag: 1.6.1@sha256:6d6c3abac41f18c8cace6e0df2961211909784c2405a905a2ac0dd3f39e2ead2
            envFrom:
              - secretRef:
                  name: chartdb-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.omux.io"
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: &port 8080

    service:
      app:
        controller: *app
        ports:
          http:
            port: *port

    serviceAccount:
      create: true
      name: *app

    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - port: http
