---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name dawarich-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Dawarich
        DATABASE_NAME: &dbname dawarich
        DATABASE_HOST: &dbhost postgres-rw.database.svc.cluster.local
        DATABASE_USERNAME: &dbuser "{{ .POSTGRES_USER }}"
        DATABASE_PASSWORD: &dbpass "{{ .POSTGRES_PASS }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: dawarich
    - extract:
        key: cloudnative-pg
