---
changelog:
  categories:
    - title: 🚨 Breaking Changes
      labels:
        - type/breaking
    - title: 🔒 Security Updates
      labels:
        - type/security
    - title: ⭐ New Features
      labels:
        - type/enhancement
    - title: 🐛 Bug Fixes
      labels:
        - type/bug
    - title: 📚 Documentation
      labels:
        - type/documentation
    - title: 🔧 Maintenance
      labels:
        - type/maintenance
  exclude:
    # Exclude automated commits from bots
    authors:
      - "github-actions[bot]"
      - "renovate[bot]"
      - "flux[bot]"
      - "bot-dan"
      - "bot-cactuar"
    # Exclude certain types of changes
    labels:
      - "type/dependency"    # Skip dependency updates
      - "area/github"        # Skip GitHub workflow changes
