---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: enabled
spec:
  affinity:
    podAntiAffinityType: required
  bootstrap:
    recovery:
      source: &src source
      recoveryTarget:
        targetTLI: "1"
  externalClusters:
    - name: *src
      plugin:
        name: &plugin barman-cloud.cloudnative-pg.io
        isWALArchiver: true
        parameters:
          barmanObjectName: &store cloudflare-r2
          serverName: postgres
  imageName: ghcr.io/cloudnative-pg/postgresql:${POSTGRESQL_VERSION}
  instances: 3
  postgresql:
    parameters:
      max_locks_per_transaction: "128"
      max_connections: "200"
      shared_buffers: 256MB
    synchronous:
      dataDurability: preferred
      method: any
      number: 1
  plugins:
    - name: *plugin
      isWALArchiver: true
      parameters:
        barmanObjectName: *store
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "4Gi"
  storage:
    resizeInUseVolumes: true
    size: 20Gi
    storageClass: openebs-hostpath
  enableSuperuserAccess: true
  superuserSecret:
    name: cloudnative-pg-secret
  monitoring:
    enablePodMonitor: true
