---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-immich
spec:
  instances: 3
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.5-v0.3.0@sha256:be3f025d79aa1b747817f478e07e71be43236e14d00d8a9eb3914146245035ba
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover
  storage:
    size: 20Gi
    storageClass: openebs-hostpath
  superuserSecret:
    name: cloudnative-pg-secret-immich
  bootstrap:
    initdb:
      database: immich
      owner: postgres
      secret:
        name: cloudnative-pg-secret-immich
  enableSuperuserAccess: true
  postgresql:
    shared_preload_libraries: ["vectors.so"]
    parameters:
      max_connections: "200"
      shared_buffers: 256MB
  resources:
    requests:
      cpu: 500m
    limits:
      memory: 2Gi
  monitoring:
    enablePodMonitor: true
  inheritedMetadata:
    annotations:
      kyverno.io/exclude: "true"
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      data:
        compression: gzip
      wal:
        compression: gzip
        maxParallel: 8
      destinationPath: s3://cloudnative-pg/
      endpointURL: https://35d4b5ef367c91eb592bf91567631e3d.r2.cloudflarestorage.com
      serverName: postgres-immich-v1
      s3Credentials:
        accessKeyId:
          name: cloudnative-pg-secret-immich
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: cloudnative-pg-secret-immich
          key: AWS_SECRET_ACCESS_KEY
