---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: cloudflare-r2
spec:
  configuration:
    data:
      compression: gzip
    destinationPath: s3://cloudnative-pg/
    endpointURL: https://35d4b5ef367c91eb592bf91567631e3d.r2.cloudflarestorage.com
    s3Credentials:
      accessKeyId:
        name: cloudnative-pg-secret
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: cloudnative-pg-secret
        key: AWS_SECRET_ACCESS_KEY
    wal:
      compression: zstd
  retentionPolicy: 30d
