---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: database
  annotations:
    external-dns.alpha.kubernetes.io/hostname: postgres.omux.io
spec:
  type: LoadBalancer
  annotations:
    lbipam.cilium.io/ips: 192.168.20.83
  externalTrafficPolicy: Local
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: postgres-immich
#   namespace: database
#   annotations:
#     external-dns.alpha.kubernetes.io/hostname: postgres-immich.omux.io
# spec:
#   type: LoadBalancer
#   ports:
#     - name: postgres-immich
#       port: 5432
#       protocol: TCP
#       targetPort: 5432
#   selector:
#     cnpg.io/cluster: postgres-immich
#     cnpg.io/instanceRole: primary
