---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: n8n-secret
    creationPolicy: Owner
    template:
      data:
        INIT_POSTGRES_DBNAME: n8n
        INIT_POSTGRES_HOST: postgres-rw.databases.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .N8N_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .N8N_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        DB_POSTGRESDB_USER: "{{ .N8N_POSTGRES_USER }}"
        DB_POSTGRESDB_PASSWORD: "{{ .N8N_POSTGRES_PASS }}"
  dataFrom:
    - extract:
        key: n8n
    - extract:
        key: cloudnative-pg
