apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: n8n
  namespace: tools
  labels:
    app.kubernetes.io/name: n8n
spec:
  hostnames:
  - "n8n.omux.io"
  parentRefs:
  - name: external
    namespace: kube-system
    sectionName: https
  rules:
  - backendRefs:
    - name: n8n
      port: 80
