---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 1h
  values:
    controllers:
      n8n:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/n8n-io/n8n
              tag: 1.118.1
            env:
              DB_SQLITE_VACUUM_ON_STARTUP: true
              DB_SQLITE_POOL_SIZE: 3
              EXECUTIONS_DATA_PRUNE: true
              EXECUTIONS_DATA_MAX_AGE: 7
              EXECUTIONS_DATA_PRUNE_MAX_COUNT: 50000
              GENERIC_TIMEZONE: "Europe/London"
              N8N_USER_FOLDER: /home/node/.n8n
              N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: false
              N8N_PROTOCOL: "https"
              N8N_PORT: &port 8080
              N8N_HOST: n8n.omux.io
              N8N_LOG_LEVEL: info
              N8N_LOG_OUTPUT: console
              N8N_RUNNERS_ENABLED: true
              N8N_BLOCK_ENV_ACCESS_IN_NODE: false
              N8N_GIT_NODE_DISABLE_BARE_REPOS: true
              N8N_ENCRYPTION_KEY:
                valueFrom:
                  secretKeyRef:
                    name: n8n-secret
                    key: N8N_ENCRYPTION_KEY
            resources:
              requests:
                cpu: 5m
                memory: 128Mi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [10000]
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
        advancedMounts:
          n8n:
            app:
              - path: /home/node/.n8n
    route:
      app:
        hostnames:
           - "{{ .Release.Name }}.omux.io"
        parentRefs:
          - name: envoy-internal
            namespace: networking
            sectionName: https
      webhooks:
        hostnames:
          - "{{ .Release.Name }}-webhook.omux.io"
        parentRefs:
          - name: envoy-external
            namespace: networking
            sectionName: https
        rules:
          - matches:
              - path:
                  value: /webhook
            backendRefs:
              - {}
    service:
      app:
        controller: n8n
        ports:
          http:
            port: *port
