---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-meta
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 30m
  path: ./infrastructure/flux/meta
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  # Flux repositories under this need flux-system hardcoded as namespace for Renovate lookups
  targetNamespace: flux-system
  timeout: 5m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-controllers
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: cluster-meta
      namespace: flux-system
  interval: 30m
  path: ./infrastructure/controllers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: false
  patches:
    - # Add Sops decryption to child Kustomizations
      patch: |
        - op: add
          path: /spec/decryption
          value:
            provider: sops
            secretRef:
              name: sops-age
      target:
        group: kustomize.toolkit.fluxcd.io
        kind: Kustomization
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: cluster-main-apps
#   namespace: flux-system
# spec:
#   decryption:
#     provider: sops
#     secretRef:
#       name: sops-age
#   dependsOn:
#     - name: cluster-meta
#       namespace: flux-system
#     - name: cluster-controllers
#       namespace: flux-system
#   interval: 30m
#   path: ./clusters/main/apps
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
#   timeout: 5m
#   wait: false
#   patches:
#     - # Add Sops decryption to child Kustomizations
#       patch: |
#         - op: add
#           path: /spec/decryption
#           value:
#             provider: sops
#             secretRef:
#               name: sops-age
#       target:
#         group: kustomize.toolkit.fluxcd.io
#         kind: Kustomization
