---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app paperless
  namespace: flux-system
spec:
  path: ./clusters/main/apps/personal/paperless/app
  targetNamespace: personal
  sourceRef:
    kind: GitRepository
    name: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  prune: true
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: cloudnative-pg-cluster
    - name: dragonfly-cluster
    - name: external-secrets-stores
    - name: democratic-csi-nfs
    - name: volsync
  postBuild:
    substitute:
      APP: *app
      HOSTNAME: paperless.omux.io
      APP_UID: "568"
      APP_GID: "568"
      VOLSYNC_CLAIM: paperless-data
      VOLSYNC_CAPACITY: 5Gi
      VOLSYNC_CACHE_CAPACITY: 5Gi
      VOLSYNC_STORAGECLASS: truenas-nfs
      VOLSYNC_SNAPSHOTCLASS: truenas-nfs
      VOLSYNC_TIME: 0 3 * * *
      VOLSYNC_PUID: "3000"
      VOLSYNC_PGID: "3000"
