---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app paperless
  namespace: &namespace personal
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cloudnative-pg-cluster
      namespace: database
    - name: dragonfly-cluster
      namespace: database
    - name: onepassword
      namespace: external-secrets
    - name: democratic-csi-nfs
      namespace: storage
    - name: volsync
      namespace: storage
  interval: 30m
  path: ./clusters/main/apps/personal/paperless/app
  postBuild:
    substitute:
      APP: *app
      HOSTNAME: paperless.omux.io
      APP_UID: "568"
      APP_GID: "568"
      VOLSYNC_CLAIM: paperless-data
      VOLSYNC_CAPACITY: 5Gi
      VOLSYNC_CACHE_CAPACITY: 5Gi
      VOLSYNC_STORAGECLASS: truenas-nfs
      VOLSYNC_SNAPSHOTCLASS: truenas-nfs
      VOLSYNC_PUID: "3000"
      VOLSYNC_PGID: "3000"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true
