---
age-keys:
  - &truenas age1fxakt4qpzgxtq8lp2mj20ryjrwslwzsggrkj2865zyde38u8tdysn3l5dy
  - &talos-main age1j05ehe53s6a3zmdgqqvj7g6hm42g0h56ga4vxsr4u52kjpagrefqnaa87c

creation_rules:
  - path_regex: infrastructure/talos/talsecret(\.sops)?\.ya?ml
    input_type: yaml
    encrypted_regex: ^(cluster|secrets|trustdinfo|certs)$
    mac_only_encrypted: true
    key_groups:
      - age:
          - *talos-main

  - path_regex: infrastructure/.+\.*(secret|secrets|deploy-key|age-key)(\.sops)?\.ya?ml
    input_type: yaml
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    key_groups:
      - age:
          - *talos-main

  - path_regex: clusters/.*(.sops)?\.ya?ml
    input_type: yaml
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    key_groups:
      - age:
          - *talos-main

  - path_regex: infrastructure/ansible/group_vars/truenas.*\.sops\.ya?ml
    input_type: yaml
    key_groups:
      - age:
          - *truenas
