---
version: '3'

set: [pipefail]
shopt: [globstar]

vars:
  BOOTSTRAP_DIR: '{{.ROOT_DIR}}/bootstrap'
  KUBERNETES_DIR: '{{.ROOT_DIR}}/infrastructure'
  TALOS_DIR: '{{.ROOT_DIR}}/talos'

env:
  KUBECONFIG: '{{.KUBERNETES_DIR}}/kubeconfig'
  MINIJINJA_CONFIG_FILE: '{{.ROOT_DIR}}/.minijinja.toml'
  SOPS_AGE_KEY_FILE: '{{.ROOT_DIR}}/age.key'
  TALOSCONFIG: '{{.TALOS_DIR}}/clusterconfig/talosconfig'
  FLUX_NAMESPACE: 'flux-system'
  CLUSTER_NAME: aeon

includes:
  bootstrap: .taskfiles/bootstrap
  flux: .taskfiles/flux
  kubernetes: .taskfiles/kubernetes
  r2: .taskfiles/r2
  talos: .taskfiles/talos/Taskfile.yaml
  workstation: .taskfiles/workstation/Taskfile.yaml
  volsync: .taskfiles/volsync

tasks:

  k9s:
    desc: Open K9s for the current cluster
    cmd: k9s --kubeconfig {{.KUBECONFIG}} --context {{.CLUSTER_NAME}}
    preconditions:
      - which k9s

  default:
    cmd: task --list
    silent: true
