---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
  - prometheusrule.yaml
configMapGenerator:
  - name: cert-manager-values
    files:
      - resources/values.yaml
configurations:
  - resources/kustomizeconfig.yaml
