---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: plex
spec:
  components:
    - ../../../../../../infrastructure/components/zeroscaler
    - ../../../../../../infrastructure/components/volsync
  dependsOn:
    - name: intel-gpu-resource-driver
      namespace: kube-system
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: ./clusters/aeon/apps/media/plex/app
  postBuild:
    substitute:
      APP: plex
      VOLSYNC_CAPACITY: 50Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
