---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: docmost
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: docmost-secret
    template:
      data:
        # App
        APP_SECRET: "{{ .DOCMOST_APP_SECRET }}"
        DATABASE_URL: "postgres://{{ .DOCMOST_DB_USER }}:{{ .DOCMOST_DB_PASSWORD }}@postgres-rw.database.svc.cluster.local/docmost?sslmode=disable"
        REDIS_URL: "redis://dragonfly.database.svc.cluster.local:6379/5"
        SMTP_HOST: "{{ .SMTP_RELAY_HOST }}"
        SMTP_PORT: "{{ .SMTP_RELAY_PORT }}"
        SMTP_USERNAME: "{{ .SMTP_RELAY_USERNAME }}"
        SMTP_PASSWORD: "{{ .SMTP_RELAY_PASSWORD }}"

        # Postgres Init
        INIT_POSTGRES_DBNAME: docmost
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .DOCMOST_DB_USER }}"
        INIT_POSTGRES_PASS: "{{ .DOCMOST_DB_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: docmost
    - extract:
        key: cloudnative-pg
    - extract:
        key: smtp-relay
