auth:
  local:
    enabled: false
  openid:
    enabled: true
    providers:
      authentik:
        name: authentik
        authurl: https://auth.omux.io/application/o/vikunja/
  ldap:
    enabled: false
