---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app wakapi
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      wakapi:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/kyteproject/postgres-init
              tag: 17
              pullPolicy: IfNotPresent
            envFrom: &envFrom
              - secretRef:
                  name: wakapi-secret
        containers:
          app:
            image:
              repository: docker.io/n1try/wakapi
              tag: 2.13.1@sha256:3f54a3e0f876d7f8182694527d5f50eafd4eb296820f96201ee509a9f9334910
            envFrom: *envFrom
            env:
              - name: ENVIRONMENT
                value: "production"
              - name: WAKAPI_PORT
                value: &port 80
              - name: WAKAPI_LISTEN_IPV4
                value: "0.0.0.0"
              - name: WAKAPI_BASE_PATH
                value: "/"
              - name: WAKAPI_DB_TYPE
                value: "postgres"
              - name: WAKAPI_DB_HOST
                valueFrom:
                  secretKeyRef:
                    name: wakapi-secret
                    key: INIT_POSTGRES_HOST
              - name: WAKAPI_DB_PORT
                value: "5432"
              - name: WAKAPI_DB_USER
                valueFrom:
                  secretKeyRef:
                    name: wakapi-secret
                    key: INIT_POSTGRES_USER
              - name: WAKAPI_DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: wakapi-secret
                    key: INIT_POSTGRES_PASS
              - name: WAKAPI_DB_NAME
                valueFrom:
                  secretKeyRef:
                    name: wakapi-secret
                    key: INIT_POSTGRES_DBNAME
              - name: WAKAPI_DB_MAX_CONNECTIONS
                value: "2"
              - name: WAKAPI_DB_SSL
                value: "false"
              - name: WAKAPI_INSECURE_COOKIES
                value: "false"
              - name: TZ
                value: "Europe/London"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/health
                    port: 80
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.omux.io"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port

    service:
      app:
        controller: *app
        ports:
          http:
            port: 80

    serviceAccount:
      create: true
      name: *app

    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - port: http
