# Source definitions
# Contains all HelmRepository resources
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: coredns
  namespace: flux-system
spec:
  interval: 1h
  url: https://coredns.github.io/helm
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 1h
  url: https://helm.cilium.io
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: postfinance
  namespace: flux-system
spec:
  interval: 1h
  url: https://postfinance.github.io/kubelet-csr-approver
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  type: oci
  interval: 1h
  url: oci://ghcr.io/prometheus-community/charts
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: spegel
  namespace: flux-system
spec:
  type: oci
  interval: 1h
  url: oci://ghcr.io/spegel-org/helm-charts
