---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name dcsi-iscsi-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        driver-config-file.yaml: |
          driver: freenas-api-iscsi
          httpConnection:
            protocol: http
            host: "${NET_TRUENAS_IP}"
            port: "80"
            apiKey: {{ .TRUENAS_API_TOKEN }}
            allowInsecure: true
          zfs:
            datasetProperties:
              "org.freenas:description": "{{`{{ parameters.[csi.storage.k8s.io/pvc/name] }}`}}"
            datasetParentName: tank/talos-applications
            detachedSnapshotsDatasetParentName: tank/talos-snapshots
            zvolCompression: gzip
            zvolDedup: false
            zvolEnableReservation: false
            zvolBlocksize: 16K
          iscsi:
            targetPortal: "${NET_TRUENAS_IP}:3260"
            targetGroups:
              - targetGroupPortalGroup: 7
                targetGroupInitiatorGroup: 18
                targetGroupAuthType: None
            namePrefix: ""
            nameSuffix: ""
            extentInsecureTpc: true
            extentXenCompat: false
            extentDisablePhysicalBlocksize: true
            extentBlocksize: 4096
            # extentRpm: "SSD"
            extentAvailThreshold: 0
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: democratic-csi
