---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actual
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: actual-secret

    template:
      data:
        ACTUAL_OPENID_CLIENT_ID: "{{ .OIDC_CLIENT_ID }}"
        ACTUAL_OPENID_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
        ACTUAL_OPENID_DISCOVERY_URL: "{{ .OIDC_URL }}"
        ACTUAL_OPENID_AUTH_METHOD: "oauth2"
  dataFrom:
    - extract:
        key: actual
