---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actual
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 1h
  values:
    controllers:
      actual:
        containers:
          app:
            image:
              repository: ghcr.io/actualbudget/actual-server
              tag: 25.10.0
            env:
              ACTUAL_PORT: &port 5006
              ACTUAL_OPENID_SERVER_HOSTNAME: https://actual.omux.io
              ACTUAL_OPENID_AUTH_METHOD: oauth2
              ACTUAL_OPENID_ENFORCE: "true"
            envFrom:
              - secret: actual-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 100Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}-data"
        advancedMounts:
          actual:
            app:
              - path: /data
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            group: Misc
        hostnames:
          - "{{ .Release.Name }}.omux.io"
        parentRefs:
          - name: envoy-internal
            namespace: networking

    service:
      app:
        ports:
          http:
            port: *port
