---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flux-telegram-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: flux-telegram-token
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        token: "{{ .FLUX_TELEGRAM_TOKEN }}"
        address: https://api.telegram.org
  dataFrom:
    - extract:
        key: flux
