---
alerting:
  pushover:
    application-token: $${GATUS_PUSHOVER_APP_TOKEN}
    user-key: $${GATUS_PUSHOVER_USER_KEY}
    priority: 1
    resolved-priority: 0
    default-alert:
      description: health-check failed
      send-on-resolved: true
      failure-threshold: 3
      success-threshold: 3

connectivity:
  checker:
    target: 10.96.0.10:53
    interval: 1m

endpoints:
  - name: Status
    group: Applications
    url: https://status.omux.io
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    client:
      dns-resolver: tcp://10.96.0.10:53
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: pushover
        send-on-resolved: true

  - name: Flux webhook
    group: Services
    url: https://flux-receiver.omux.io
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    client:
      dns-resolver: tcp://10.96.0.10:53
    conditions:
      - "[STATUS] == 404"
    alerts:
      - type: pushover
        send-on-resolved: true

  # - name: Minio
  #   group: Services
  #   url: https://minio.omux.io/minio/health/live
  #   interval: 1m
  #   ui:
  #     hide-hostname: true
  #     hide-url: true
  #   client:
  #     dns-resolver: tcp://10.96.0.10:53
  #   conditions:
  #     - "[STATUS] == 200"
  #   alerts:
  #     - type: pushover
  #       send-on-resolved: true

  - name: SSO
    group: Services
    url: http://authentik.security.svc.cluster.local
    interval: 1m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: pushover
        send-on-resolved: true

metrics: true

storage:
  type: postgres
  path: postgres://$${INIT_POSTGRES_USER}:$${INIT_POSTGRES_PASS}@$${INIT_POSTGRES_HOST}:5432/$${INIT_POSTGRES_DBNAME}?sslmode=disable
  caching: true

ui:
  title: Status | Gatus
  header: Status
  link: https://github.com/kyteproject
  buttons:
    - name: Github
      link: https://github.com/kyteproject
    - name: Homelab
      link: https://github.com/kyteproject/gitops-homelab

web:
  port: $${GATUS_WEB_PORT}
