---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gatus
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gatus-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # For initial DB setup
        INIT_POSTGRES_SUPER_USER: "postgres"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # For Gatus operation
        INIT_POSTGRES_DBNAME: "gatus"
        INIT_POSTGRES_HOST: "postgres-rw.database.svc.cluster.local"
        INIT_POSTGRES_USER: "{{ .GATUS_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .GATUS_POSTGRES_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: gatus
