---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - externalsecret.yaml
  - release.yaml
  - rbac.yaml
configMapGenerator:
  - name: gatus-configmap
    files:
      - config.yaml
generatorOptions:
  disableNameSuffixHash: true
