---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: truenas-api-token
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: truenas-api-token
    template:
      data:
        token: "{{ .TRUENAS_API_TOKEN }}"
  dataFrom:
    - extract:
        key: truenas
