---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - qbittorrent/ks.yaml
  # Add other media apps as needed
components:
  - ../../../../infrastructure/flux/components/alerts
  - ../../../../infrastructure/flux/components/namespace
  - ../../../../infrastructure/flux/components/sops
