---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wakapi
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: wakapi-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        INIT_POSTGRES_DBNAME: wakapi
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .WAKAPI_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .WAKAPI_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        WAKAPI_PASSWORD_SALT: "{{ .WAKAPI_PASSWORD_SALT }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: wakapi
