---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: chartdb
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: chartdb-secret
    creationPolicy: Owner
    template:
      data:
        OPENAI_API_KEY: "{{ .OPENAI_API_KEY }}"
  dataFrom:
    - extract:
        key: openai
