---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app chartdb
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      chartdb:
        containers:
          app:
            image:
              repository: ghcr.io/kyteproject/chartdb
              tag: 1.9.0@sha256:20fb27794eb6013e2b5791ee8c9d6b1f5cf835485eb2bb16b9e244fd487afa62
            envFrom:
              - secretRef:
                  name: chartdb-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.omux.io"
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: &port 8080

    service:
      app:
        controller: *app
        ports:
          http:
            port: *port

    serviceAccount:
      create: true
      name: *app

    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - port: http
        selector:
          matchLabels:
            app.kubernetes.io/name: *app
            app.kubernetes.io/instance: *app
