---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: chartdb
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 1h
  values:
    controllers:
      chartdb:
        containers:
          app:
            image:
              repository: ghcr.io/chartdb/chartdb
              tag: 1.16.0@sha256:7077687c230ace08e6b7078d69628a3049c690615e66561ea8727440abc27dfc
            env:
              DISABLE_ANALYTICS: true
            envFrom:
              - secretRef:
                  name: chartdb-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.omux.io"
        parentRefs:
          - name: envoy-external
            namespace: networking
            sectionName: https
    service:
      app:
        ports:
          http:
            port: 8080
