---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${APP}"
spec:
  accessModes: ["${VOLSYNC_ACCESSMODES:-ReadWriteOnce}"]
  storageClassName: "${VOLSYNC_STORAGECLASS:-ceph-block}"
  resources:
    requests:
      storage: "${VOLSYNC_CAPACITY:-5Gi}"
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "${APP}-dst"
