---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app qbittorrent
  namespace: &namespace media
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../../../infrastructure/components/keda
    - ../../../../../../infrastructure/components/volsync
  dependsOn:
    - name: openebs
      namespace: storage
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: ./clusters/aeon/apps/media/qbittorrent/app
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 2Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
