apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: truenas
  namespace: cert-manager
spec:
  secretName: truenas-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "tank.lan"
  dnsNames:
    - "tank.lan"
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
