---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app qbittorrent
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      qbittorrent:
        containers:
          app:
            image:
              repository: ghcr.io/kyteproject/qbittorrent
              tag: 5.0.3@sha256:2bb788a97695b4045f575ba646141b4a4f73069be5a296e7440cf8e96d45d682
            env:
              QBT_TORRENTING_PORT: &bittorrentPort 50413
              QBT_WEBUI_PORT: &port 8080
              TZ: Europe/London
              # QBT_Preferences__WebUI__LocalHostAuth: false
              # QBT_Preferences__WebUI__AuthSubnetWhitelistEnabled: true
              # QBT_Preferences__WebUI__AuthSubnetWhitelist: |-
              #   10.244.0.0/16, 192.168.10.0/24
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 3
                  failureThreshold: 5
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 8Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: [ALL]

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10000
        runAsGroup: 10000
        fsGroup: 10000
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [65536]

    ingress:
      app:
        className: internal
        # annotations:
        #   authentik.home.arpa/enabled: "true"
        #   nginx.ingress.kubernetes.io/auth-signin: |-
        #     https://qb.omux.io/outpost.goauthentik.io/start?rd=$escaped_request_uri
        #   gethomepage.dev/enabled: "true"
        #   gethomepage.dev/group: Media
        #   gethomepage.dev/name: QBittorrent
        #   gethomepage.dev/icon: qbittorrent.svg
        #   gethomepage.dev/widget.type: qbittorrent
        #   gethomepage.dev/widget.url: http://qbittorrent-app.downloads
        hosts:
          - host: "{{ .Release.Name }}.omux.io"
            paths: &paths
              - path: /
                service:
                  identifier: app
                  port: http
          - host: qb.omux.io
            paths: *paths

    persistence:
      config:
        existingClaim: *app
      media:
        existingClaim: media-storage
        globalMounts:
          - path: /data
            subPath: torrents
      tmp:
        type: emptyDir

    service:
      app:
        controller: *app
        nameOverride: *app
        ports:
          http:
            port: *port
      bittorrent:
        controller: *app
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 192.168.20.2
        ports:
          bittorrent-tcp:
            port: *bittorrentPort
            protocol: TCP
          bittorrent-udp:
            port: *bittorrentPort
            protocol: UDP
