---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: &email dan@omux.dev
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: *email
            apiTokenSecretRef:
              name: cloudflare-issuer-secret
              key: CLOUDFLARE_API_TOKEN
        selector:
          dnsZones: ["omux.io"]
