---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb
spec:
  $patch: replace
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: "8Gi"
  storageClassName: "ceph-block"
  volumeMode: "Filesystem"
