---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: paperless-secret
    template:
      data:
        PAPERLESS_ADMIN_USER: "{{ .PAPERLESS_ADMIN_USER }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .PAPERLESS_ADMIN_PASS }}"
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
        PAPERLESS_REDIS: "redis://dragonfly.database.svc.cluster.local:6379/4"
        PAPERLESS_TIME_ZONE: "Europe/London"
        PAPERLESS_APPS: "allauth.socialaccount.providers.openid_connect"
        PAPERLESS_WEBSERVER_WORKERS: "2"
        PAPERLESS_TASK_WORKERS: "2"
        PAPERLESS_URL: "https://paperless.omux.io"
        PAPERLESS_CONSUMPTION_DIR: "/data/nas/consume"
        PAPERLESS_DATA_DIR: "/usr/src/paperless/data"
        PAPERLESS_EXPORT_DIR: "/data/nas/export"
        PAPERLESS_MEDIA_ROOT: "/data/nas/media"
        PAPERLESS_CONSUMER_POLLING: "360"
        PAPERLESS_CONSUMER_RECURSIVE: "true"
        PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"
        # OCR
        PAPERLESS_OCR_LANGUAGES: "eng"
        PAPERLESS_OCR_LANGUAGE: "eng"
        PAPERLESS_OCR_SKIP_ARCHIVE_FILE: "with_text"
        PAPERLESS_OCR_USER_ARGS: '{"invalidate_digital_signatures": true}'
        PAPERLESS_FILENAME_FORMAT: "{{ `{{ correspondent }}/{{ created_year }}/{{ correspondent }}_{{ document_type }}_{{ created }}` }}"
        PAPERLESS_TIKA_ENABLED: "true"
        PAPERLESS_TIKA_ENDPOINT: "http://tika.tools.svc.cluster.local:80"
        PAPERLESS_GOTENBERG_ENDPOINT: "http://gotenberg.tools.svc.cluster.local:3000"
        # OIDC
        PAPERLESS_ACCOUNT_ALLOW_SIGNUPS: "false"
        PAPERLESS_SOCIALACCOUNT_ALLOW_SIGNUPS: "true"
        PAPERLESS_SOCIAL_AUTO_SIGNUP: "true"
        PAPERLESS_SOCIAL_ACCOUNT_SYNC_GROUPS: "true"
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: |-
          {
            "openid_connect": {
                "SCOPE": [
                    "openid",
                    "profile",
                    "email"
                ],
                "OAUTH_PKCE_ENABLED": true,
                "APPS": [
                    {
                        "provider_id": "authentik",
                        "name": "authentik",
                        "client_id": "{{ .PAPERLESS_CLIENT_ID }}",
                        "secret": "{{ .PAPERLESS_CLIENT_SECRET }}",
                        "settings": {
                            "server_url": "https://auth.omux.io/application/o/paperless/.well-known/openid-configuration",
                            "claims": {"username": "email"}
                        }
                    }
                ]
            }
          }
        PAPERLESS_LOGOUT_REDIRECT_URL: "https://auth.omux.io/application/o/paperless/end-session/"
        PAPERLESS_AUTO_LOGIN: "true"
        PAPERLESS_AUTO_CREATE: "true"
  dataFrom:
    - extract:
        key: paperless
