---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: omux-io
spec:
  secretName: omux-io-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: omux.io
  dnsNames: ["omux.io", "*.omux.io"]
