---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./release.yaml
configMapGenerator:
  - name: cilium-values
    files:
      - values.yaml=./resources/values.yaml
configurations:
  - ./resources/kustomizeconfig.yaml
