---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - externalsecret.yaml
  - release.yaml
configMapGenerator:
  - name: recyclarr-configmap
    files:
      - resources/recyclarr.yml
generatorOptions:
  disableNameSuffixHash: true
