---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app roon
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      roon:
        containers:
          app:
            image:
              repository: mackid1993/docker-roonserver:latest
            env:
              TZ: Europe/London
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 4Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            ports:
              - containerPort: 9101
                protocol: TCP
              - containerPort: 9102
                protocol: TCP
              - containerPort: 9103
                protocol: TCP
              - containerPort: 9104
                protocol: TCP
              - containerPort: 9105
                protocol: TCP
              - containerPort: 9106
                protocol: TCP
              - containerPort: 9107
                protocol: TCP
              - containerPort: 9108
                protocol: TCP
              - containerPort: 9109
                protocol: TCP
              - containerPort: 9110
                protocol: TCP
              - containerPort: 9003
                protocol: UDP
    defaultPodOptions:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [{
            "name": "multus-iot",
            "namespace": "networking",
            "ips": ["192.168.40.200/24"]
          }]
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      app:
        type: emptyDir
        globalMounts:
          - path: /app
      data:
        type: emptyDir
        globalMounts:
          - path: /data
      music:
        type: emptyDir
        globalMounts:
          - path: /music
      backup:
        type: emptyDir
        globalMounts:
          - path: /backup
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.omux.io"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: &port 9100
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
