---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: sources
  path: ./apps/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-homelab
  wait: true
  timeout: 5m
