---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airtrail
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: airtrail-secret
    template:
      data:
        # App
        DB_URL: "postgres://airtrail:{{ .AIRTRAIL_DB_PASSWORD }}@postgres-rw.database.svc.cluster.local:5432/airtrail"

        # Postgres Init
        INIT_POSTGRES_DBNAME: airtrail
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: airtrail
        INIT_POSTGRES_PASS: "{{ .AIRTRAIL_DB_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: airtrail
    - extract:
        key: cloudnative-pg
