---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - namespace.yaml
  # - agregarr/ks.yaml
  - audiobookshelf/ks.yaml
  - autobrr/ks.yaml
  - bazarr/ks.yaml
  - beets/ks.yaml
  - bookboss/ks.yaml
  - brrpolice/ks.yaml
  - jellyfin/ks.yaml
  - koito/ks.yaml
  - komf/ks.yaml
  - komga/ks.yaml
  # - maintainerr/ks.yaml
  - musicgrabber/ks.yaml
  - navidrome/ks.yaml
  # - plex/ks.yaml
  - prowlarr/ks.yaml
  - qbittorrent/ks.yaml
  - qui/ks.yaml
  - radarr/ks.yaml
  - recyclarr/ks.yaml
  - sabnzbd/ks.yaml
  - seerr/ks.yaml
  - sonarr/ks.yaml
  - soulsync/ks.yaml
  - suwayomi/ks.yaml
  # - tautulli/ks.yaml
  - upbrr/ks.yaml
  # - wizarr/ks.yaml
components:
  - ../../../../infrastructure/components/namespace
