---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name audiobookshelf-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # These don't work yet
        AUDIOBOOKSHELF_OIDC_DISCOVERY_URL: "https://id.omux.io/application/o/audiobookshelf/.well-known/openid-configuration"
        AUDIOBOOKSHELF_OIDC_CLIENT_ID: "{{ .OIDC_CLIENT_ID }}"
        AUDIOBOOKSHELF_OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: audiobookshelf
