---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
resources:
  - democratic-csi/ks.yaml
  - openebs/ks.yaml
  - snapshot-controller/ks.yaml
  - volsync/ks.yaml
components:
  - ../../flux/components/common
