apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-controllers
  namespace: flux-system
spec:
  interval: 15m
  retryInterval: 3m
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./infrastructure/controllers/kube-system
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
  patches:
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: all
        spec:
          decryption:
            provider: sops
            secretRef:
              name: sops-age
          postBuild:
            substituteFrom:
              - kind: ConfigMap
                name: cluster-settings
              - kind: Secret
                name: cluster-secrets
      target:
        group: kustomize.toolkit.fluxcd.io
        kind: Kustomization
        labelSelector: substitution.flux.home.arpa/disabled notin (true)
# # ---
# # apiVersion: kustomize.toolkit.fluxcd.io/v1
# # kind: Kustomization
# # metadata:
# #   name: infra-configs
# #   namespace: flux-system
# # spec:
# #   targetNamespace: kube-system
# #   dependsOn:
# #     - name: infra-controllers
# #   interval: 1h
# #   retryInterval: 1m
# #   timeout: 5m
# #   sourceRef:
# #     kind: GitRepository
# #     name: flux-system
# #   path: ./infrastructure/configs
# #   prune: true
