---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  endpoints:
    - dnsName: external.omux.io
      recordTTL: 1
      recordType: CNAME
      targets:
        - 4ab16931-237a-4623-aa90-c0aa5d062506.cfargotunnel.com
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "true"

