---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflared
  labels:
    thisisstupid.omux.io: external
spec:
  endpoints:
    - dnsName: external.omux.io
      recordType: CNAME
      targets: ["${CLOUDFLARE_TUNNEL_MAIN_ID}.cfargotunnel.com"]
