---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dnsendpoint.yaml
  - externalsecret.yaml
  - release.yaml
configMapGenerator:
  - name: cloudflared-configmap
    files:
      - config.yaml
generatorOptions:
  disableNameSuffixHash: true
