---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - externalsecret.yaml
  - release.yaml
  - dnsendpoint.yaml
configMapGenerator:
  - name: cloudflared-configmap
    files:
      - config.yaml=./resources/config.yaml
generatorOptions:
  disableNameSuffixHash: true
vars:
  - name: TUNNEL_ID
    objref:
      kind: Secret
      name: cloudflare-tunnel-id-secret
      apiVersion: v1
    fieldref:
      fieldpath: data.CLOUDFLARE_TUNNEL_ID
