apiVersion: v1
kind: Secret
metadata:
    name: sops-age
stringData:
    age.agekey: ENC[AES256_GCM,data:jB02Syf5JDyU8Rlx+0JpeGDFxbt7Pf587R57e+xVfBf4ReMHjtJ8bg+GNhrOHHUkn38NpH9bVwZFFDXHx0Z+FS3L5Kpa/5/8hxGuem8i0I4uoX4ARWp0LjPcZe+yC0g7c33wbCWdwokChMbiXnPD0anLW7IU4Tz2diJXCp5izLZGXuYmaI4v44JaM4eAVJ2lRxTNaDuh5/MZ/o5H1qeQnBb9QAbBEaUYxKEU45hTv8E6en30u+Ed9g==,iv:+lQ6DJGODZ3qGrpQwoi8A35ozw/iLipghJ075o8eCdk=,tag:YkYK/YGjWaGG3ESWEdck/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j05ehe53s6a3zmdgqqvj7g6hm42g0h56ga4vxsr4u52kjpagrefqnaa87c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvcnVWZkdIRU1MUy85L1o1
            WEkzUHd6MjRUUzRSMjlTcnN0Zi8vbzN2NmpFCkZMK1F0NC9JdWxlSmFZenJWSlRq
            U1Mzb0t3R1J3QnMyc2NkNTNtQVBobjAKLS0tIEJ4aE15cXdrRlJTMFhIY1V2dmZr
            QURRY0toWFlKRGxENjJnaklneWxBTlEKnd0xCO3IOBCiCg3fZydIBd+5d1nmjgsp
            3jRRZoRR8ekP/5RculXY7PETFQVI0W1Ih4UeogfKi6M95AZjM1VR4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-27T12:49:52Z"
    mac: ENC[AES256_GCM,data:vg9CdVW1EdRjRQW3Mykx555twNclpTlgaNpxylNjNtBAXAZ48ObVJQZk0Pvz+zf078P6MXRtxUabzFYSfzZuMZSyTWCjQkX4Wiq/WM4UHdW15N98n/Nb0KmBhGTxieG5VAoCYia1gjH18sQAKQw0oZfgbrN0+wseSTSgRtabiFM=,iv:Tk7nInEoxe3HV9WLlZz6YEYRONvaxMd5MpPNiFSj5Ro=,tag:KZ8XupJV5OQ5y+yuCzuMdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.1
