---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: erpnext
spec:
  interval: 1h
  chart:
    spec:
      chart: erpnext
      version: "7.0.168"
      sourceRef:
        kind: HelmRepository
        name: erpnext
        namespace: flux-system
      interval: 1h
  values:
    image:
      repository: frappe/erpnext-worker
      tag: v15.53.1

    mariadb:
      enabled: true
      auth:
        rootPassword: "${ERPNEXT_DB_ROOT_PASSWORD}"
        password: "${ERPNEXT_DB_PASSWORD}"
        username: erpnext
        database: erpnext
      primary:
        persistence:
          enabled: true
          storageClass: ceph-block
          size: 20Gi
      secondary:
        persistence:
          enabled: true
          storageClass: ceph-block
          size: 20Gi

    redis:
      enabled: true
      auth:
        password: "${ERPNEXT_REDIS_PASSWORD}"
      master:
        persistence:
          enabled: true
          storageClass: ceph-filesystem
          size: 8Gi
      replica:
        persistence:
          enabled: true
          storageClass: ceph-filesystem
          size: 8Gi

    persistence:
      worker:
        enabled: true
        storageClass: ceph-filesystem
        size: 8Gi
        accessMode: ReadWriteMany
      assets:
        enabled: true
        storageClass: ceph-filesystem
        size: 8Gi
        accessMode: ReadWriteMany

    nginx:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          memory: 256Mi

    configurator:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          memory: 256Mi

    worker:
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          memory: 1Gi

    scheduler:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          memory: 256Mi

    # Site configuration
    siteName: erp.${SECRET_DOMAIN}
    adminPassword: "${ERPNEXT_ADMIN_PASSWORD}"

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.omux.io"
          - erp.omux.io
        parentRefs:
          - name: envoy-internal
            namespace: networking
            sectionName: https
