---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich
  namespace: &namespace personal
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../../../infrastructure/components/volsync
  dependsOn:
    - name: immich-db
      namespace: personal
    - name: onepassword-store
      namespace: external-secrets
    - name: openebs
      namespace: storage
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: ./clusters/aeon/apps/personal/immich/app
  postBuild:
    substitute:
      APP: *app
      HOSTNAME: photos.omux.io
      APP_UID: "568"
      APP_GID: "568"
      VOLSYNC_CAPACITY: 10Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich-db
  namespace: personal
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: immich-db
  dependsOn:
    - name: cloudnative-pg
      namespace: database
    - name: onepassword-store
      namespace: external-secrets
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: ./clusters/aeon/apps/personal/immich/db
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: database
  wait: true
  timeout: 5m
