---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich
  namespace: &namespace personal
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: onepassword-stores
      namespace: external-secrets
    - name: democratic-csi-nfs
      namespace: storage
    - name: dragonfly-cluster
      namespace: database
    - name: cloudnative-pg-cluster
      namespace: database
  interval: 30m
  path: ./clusters/aeon/apps/personal/immich/app
  postBuild:
    substitute:
      APP: *app
      HOSTNAME: photos.omux.io
      APP_UID: "568"
      APP_GID: "568"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true
