---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubelet-csr-approver
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: kubelet-csr-approver
      version: 1.2.4
      sourceRef:
        kind: HelmRepository
        name: postfinance
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: coredns
      namespace: kube-system
  valuesFrom:
    - kind: ConfigMap
      name: kubelet-csr-approver-helm-values
  values:
    metrics:
      enable: true
      serviceMonitor:
        enabled: true
