---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi-nfs
spec:
  interval: 10m
  chart:
    spec:
      chart: democratic-csi
      version: 0.14.7
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: snapshot-controller
      namespace: storage
  values:
    controller:
      replicaCount: 2
      podAnnotations:
        secret.reloader.stakater.com/reload: &secret dcsi-nfs-secret
        reloader.stakater.com/auto: "true"
      driver:
        image: ghcr.io/democratic-csi/democratic-csi:v1.9.3
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Equal
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      priorityClassName: system-cluster-critical
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: "DoNotSchedule"
          labelSelector:
            matchLabels:
              app.kubernetes.io/csi-role: controller
              app.kubernetes.io/instance: democratic-csi-nfs
    node:
      podAnnotations:
        secret.reloader.stakater.com/reload: *secret
      cleanup:
        image: public.ecr.aws/docker/library/busybox:1.37.0
      driver:
        image: ghcr.io/democratic-csi/democratic-csi:v1.9.3
    csiProxy:
      image: ghcr.io/democratic-csi/csi-grpc-proxy:v0.5.6
    csiDriver:
      name: "org.democratic-csi.nfs"

    storageClasses:
      - name: truenas-nfs
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: nfs
          detachedVolumesFromSnapshots: true
          detachedVolumesFromVolumes: true
        mountOptions:
          - "nfsvers=4.2"
          - "nconnect=8"
          - "hard"
          - "noatime"
          - "nodiratime"
          - "rsize=262144"    # Larger read sizes for better streaming
          - "wsize=262144"    # Larger write sizes for uploads
          - "tcp"             # Force TCP for reliability
        secrets:
          provisioner-secret:
          controller-publish-secret:
          node-stage-secret:
          node-publish-secret:
          controller-expand-secret:

    volumeSnapshotClasses:
      - name: truenas-nfs
        driver: org.democratic-csi.nfs
        deletionPolicy: Delete
        parameters:
          detachedSnapshots: false

    driver:
      config:
        driver: freenas-api-nfs
      existingConfigSecret: *secret
