---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-immich
  namespace: database
spec:
  description: Postgresql cluster for Immich
  instances: 1
  # renovate: datasource=docker depName=ghcr.io/tensorchord/cloudnative-pgvecto.rs
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:17.5
  storage:
    size: 10Gi
    storageClass: ceph-block
  enableSuperuserAccess: true
  superuserSecret:
    name: cloudnative-pg-secret-immich
  postgresql:
    shared_preload_libraries: ["vchord.so"]
    parameters:
      max_connections: "200"
      shared_buffers: 256MB
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  primaryUpdateStrategy: unsupervised
  monitoring:
    enablePodMonitor: true
  bootstrap:
    initdb:
      database: immich
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
      secret:
        name: cloudnative-pg-secret-immich
  backup:
    retentionPolicy: 30d
    barmanObjectStore: &barmanObjectStore
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://cloudnative-pg/immich/
      endpointURL: https://35d4b5ef367c91eb592bf91567631e3d.r2.cloudflarestorage.com
      serverName: postgres-immich-v2
      s3Credentials:
        accessKeyId:
          name: cloudnative-pg-secret-immich
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: cloudnative-pg-secret-immich
          key: AWS_SECRET_ACCESS_KEY
  # # Note: previousCluster needs to be set to the name of the previous
  # # cluster when recovering from an existing cnpg cluster
  # bootstrap:
  #   recovery:
  #     source: &previousCluster postgres-immich-v2
  # # Note: externalClusters is needed when recovering from an existing cnpg cluster
  # externalClusters:
  #   - name: *previousCluster
  #     barmanObjectStore:
  #       <<: *barmanObjectStore
  #       serverName: *previousCluster
