---
apiVersion: v1
kind: Service
metadata:
  name: postgres-immich
  namespace: database
  annotations:
    external-dns.alpha.kubernetes.io/hostname: postgres-immich.omux.io
    lbipam.cilium.io/ips: 192.168.20.84
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: postgres-immich
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres-immich
    cnpg.io/instanceRole: primary

