---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: radicale
spec:
  components:
    - ../../../../../../infrastructure/components/volsync
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: ./clusters/aeon/apps/personal/radicale/app
  postBuild:
    substitute:
      APP: radicale
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: personal
