---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-configmap
data:
  DB_PORT: "5432"
  NODE_ENV: "production"
  REDIS_HOSTNAME: dragonfly.database.svc.cluster.local
  REDIS_PORT: "6379"
  REDIS_DBINDEX: "3"
  IMMICH_SERVER_URL: http://immich-server.personal.svc.cluster.local:3001
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.personal.svc.cluster.local:3003
