---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: personal
resources:
  - externalsecret.yaml
  - release.yaml
  - pvc.yaml
configMapGenerator:
  - name: immich-config-tpl
    files:
      - ./config/immich.config.json
generatorOptions:
  disableNameSuffixHash: true
labels:
  - pairs:
      app.kubernetes.io/name: immich
      app.kubernetes.io/instance: immich
      app.kubernetes.io/part-of: immich
