---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: windmill
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: windmill-secret
    template:
      data:
        WINDMILL_POSTGRESQL__NAME: &dbName windmill
        WINDMILL_POSTGRESQL__HOST: &dbHost postgres-rw.database.svc.cluster.local
        WINDMILL_POSTGRESQL__USER: &dbUser "{{ .WINDMILL_POSTGRESQL__USER }}"
        WINDMILL_POSTGRESQL__PASSWORD: &dbPass "{{ .WINDMILL_POSTGRESQL__PASSWORD }}"
        # Windmill chart reads this key via windmill.databaseUrlSecretKey
        url: postgres://{{ .WINDMILL_POSTGRESQL__USER }}:{{ .WINDMILL_POSTGRESQL__PASSWORD }}@postgres-rw.database.svc.cluster.local/windmill?sslmode=disable

        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: windmill
    - extract:
        key: cloudnative-pg
