---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: windmill
spec:
  chart:
    spec:
      chart: windmill
      version: 4.0.38
      sourceRef:
        kind: HelmRepository
        name: windmill
        namespace: flux-system
  interval: 1h
  values:
    postgresql:
      enabled: false
    ingress:
      enabled: false
    httproute:
      enabled: true
      parentRefs:
        - name: envoy-internal
          namespace: networking
          sectionName: https
    windmill:
      appReplicas: 1
      baseDomain: windmill.omux.io
      baseProtocol: https
      databaseUrlSecretName: windmill-secret
      databaseUrlSecretKey: url
      app:
        annotations:
          secret.reloader.stakater.com/reload: windmill-secret
        initContainers:
          - name: init-db
            image: ghcr.io/kyteproject/postgres-init:17.7
            imagePullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: windmill-secret
          - name: init-windmill-roles
            image: public.ecr.aws/docker/library/postgres:17
            imagePullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: windmill-secret
            command:
              - /bin/sh
              - -ec
              - /var/run/grants.sh
            volumeMounts:
              - name: grants
                readOnly: true
                subPath: grants.sh
                mountPath: /var/run/grants.sh
        volumes:
          - name: grants
            configMap:
              name: windmill-grants
              defaultMode: 509
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
          limits:
            memory: 1Gi
