---
apiVersion: v1
kind: Pod
metadata:
  name: network-test-pod
  namespace: networking
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [{
        "name": "multus-iot",
        "namespace": "networking",
        "ips": ["192.168.40.200/24"]
      }]
spec:
  containers:
    - name: networking-pod
      command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
      image: nicolaka/netshoot