---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools
resources:
  - atuin/ks.yaml
  - changedetection/ks.yaml
  - chartdb/ks.yaml
  - gotenberg/ks.yaml
  - n8n/ks.yaml
  - tika/ks.yaml
components:
  - ../../../../infrastructure/components/namespace
