---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mariadb
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mariadb-secret
    template:
      data:
        mariadb-root-password: "{{ .MARIADB_ROOT_PASSWORD }}"
  dataFrom:
    - extract:
        key: mariadb
