---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mariadb
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mariadb-secret
    template:
      data:
        mariadb-root-password: "{{ .MARIADB_ROOT_PASSWORD }}"
        mariadb-password: "{{ .BOOKSTACK_MARIADB_PASSWORD }}"
        mariadb-user: "{{ .BOOKSTACK_MARIADB_USER }}"
        mariadb-database: "{{ .BOOKSTACK_MARIADB_DB }}"

        password: "{{ .BOOKSTACK_MARIADB_PASSWORD }}"
        user: "{{ .BOOKSTACK_MARIADB_USER }}"
        database: "{{ .BOOKSTACK_MARIADB_DB }}"

        MYSQL_USER:  "{{ .BOOKSTACK_MARIADB_USER }}"
        MYSQL_DATABASE: "{{ .BOOKSTACK_MARIADB_DB }}"
        MYSQL_PASSWORD: "{{ .BOOKSTACK_MARIADB_PASSWORD }}"
        MARIADB_USER:  "{{ .BOOKSTACK_MARIADB_USER }}"
        MARIADB_DATABASE: "{{ .BOOKSTACK_MARIADB_DB }}"
        MARIADB_PASSWORD: "{{ .BOOKSTACK_MARIADB_PASSWORD }}"
  dataFrom:
    - extract:
        key: mariadb
    - extract:
        key: bookstack
