---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: mariadb
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 20.4.2
  url: oci://registry-1.docker.io/bitnamicharts/mariadb
  verify:
    provider: cosign
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mariadb
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: mariadb
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    auth:
      usePasswordFiles: false
      existingSecret: mariadb-secret
    metrics:
      enabled: true
      resourcesPreset: small
      serviceMonitor:
        enabled: true
    primary:
      resourcesPreset: small
      persistence:
        enabled: true
        existingClaim: *app
    initdbScripts:
      create-bookstack.sql: |
        CREATE DATABASE IF NOT EXISTS bookstackapp;
        CREATE USER IF NOT EXISTS 'bookstack'@'%' IDENTIFIED BY '${BOOKSTACK_MARIADB_PASSWORD}';
        GRANT ALL PRIVILEGES ON bookstackapp.* to 'bookstack'@'%';