---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: mariadb
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 20.4.2
  url: oci://registry-1.docker.io/bitnamicharts/mariadb
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mariadb
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: mariadb
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    auth:
      rootPassword:
        valueFrom:
          secretKeyRef:
            name: mariadb-secret
            key: mariadb-root-password
      database:
        valueFrom:
          secretKeyRef:
            name: mariadb-secret
            key: BOOKSTACK_MARIADB_DB
      username:
        valueFrom:
          secretKeyRef:
            name: mariadb-secret
            key: BOOKSTACK_MARIADB_USER
      password:
        valueFrom:
          secretKeyRef:
            name: mariadb-secret
            key: BOOKSTACK_MARIADB_PASSWORD
    metrics:
      enabled: true
      resourcesPreset: small
      serviceMonitor:
        enabled: true
    primary:
      resourcesPreset: small
      persistence:
        enabled: true
        existingClaim: *app
    extraEnvVars:
      - name: MARIADB_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mariadb-secret
            key: mariadb-root-password
      - name: MARIADB_DATABASE
        valueFrom:
          secretKeyRef:
            name: mariadb-secret
            key: BOOKSTACK_MARIADB_DB
      - name: MARIADB_USER
        valueFrom:
          secretKeyRef:
            name: mariadb-secret
            key: BOOKSTACK_MARIADB_USER
      - name: MARIADB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mariadb-secret
            key: BOOKSTACK_MARIADB_PASSWORD