---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hoarder
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: hoarder-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        OPENAI_API_KEY: "{{ .OPENAI_API_KEY }}"
        MEILI_MASTER_KEY: "{{ .MEILI_MASTER_KEY }}"
        NEXTAUTH_SECRET: "{{ .NEXTAUTH_SECRET }}"
        NEXT_PUBLIC_SECRET: "{{ .NEXT_PUBLIC_SECRET }}"
  dataFrom:
    - extract:
        key: hoarder
    - extract:
        key: openai
