---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hoarder-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: Hoarder
        group: Applications
        url: https://hoarder.omux.io
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          dns-resolver: tcp://192.168.10.1:53
        conditions:
          - "[STATUS] == 200"
