---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app hoarder
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      hoarder:
        containers:
          app:
            image:
              repository: ghcr.io/hoarder-app/hoarder
              tag: release
            env:
              DATA_DIR: /data
              MEILI_ADDR: http://localhost:7700
              BROWSER_WEB_URL: http://localhost:9222
            envFrom:
              - secretRef:
                  name: &secret hoarder-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 3000
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: [ALL]
          chrome:
            image:
              repository: gcr.io/zenika-hub/alpine-chrome
              tag: "123"
            args:
              - chromium-browser
              - --headless
              - --no-sandbox
              - --disable-gpu
              - --disable-dev-shm-usage
              - --remote-debugging-address=0.0.0.0
              - --remote-debugging-port=9222
              - --hide-scrollbars
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: [ALL]
          search:
            image:
              repository: getmeili/meilisearch
              tag: v1.11.1
            env:
              MEILI_NO_ANALYTICS: "true"
            envFrom:
              - secretRef:
                  name: *secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: [ALL]

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
          chrome:
            port: 9222
          search:
            port: 7700

    ingress:
      app:
        className: internal
        hosts:
          - host: "{{ .Release.Name }}.omux.io"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      data:
        existingClaim: hoarder-data
        advancedMounts:
          hoarder:
            app:
              - path: /data
      search:
        existingClaim: hoarder-search
        advancedMounts:
          hoarder:
            search:
              - path: /meili_data
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
      run:
        type: emptyDir
        globalMounts:
          - path: /run
      dbus:
        type: emptyDir
        advancedMounts:
          hoarder:
            chrome:
              - path: /var/run/dbus
      fontconfig:
        type: emptyDir
        advancedMounts:
          hoarder:
            chrome:
              - path: /usr/share/fontconfig
