---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app hoarder
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      web:
        containers:
          web:
            image:
              repository: ghcr.io/hoarder-app/hoarder
              tag: 0.21.0
            env:
              MEILI_ADDR: http://hoarder-meilisearch:7700
              BROWSER_WEB_URL: http://hoarder-chrome:9222
              DATA_DIR: /data
              NEXTAUTH_URL: https://hoarder.omux.io
              DISABLE_SIGNUPS: false
              OAUTH_WELLKNOWN_URL: https://id.omux.io/application/o/hoarder/.well-known/openid-configuration
              OAUTH_PROVIDER_NAME: authentik
              OAUTH_ALLOW_DANGEROUS_EMAIL_ACCOUNT_LINKIN: true
              DISABLE_PASSWORD_AUTH: true
            envFrom:
              - secret: hoarder-secret

      chrome:
        containers:
          chrome:
            image:
              repository: gcr.io/zenika-hub/alpine-chrome
              tag: 124
            command:
              - chromium-browser
              - --headless
              - --no-sandbox
              - --disable-gpu
              - --disable-dev-shm-usage
              - --remote-debugging-address=0.0.0.0
              - --remote-debugging-port=9222
              - --hide-scrollbars

      meilisearch:
        containers:
          meilisearch:
            image:
              repository: getmeili/meilisearch
              tag: v1.6
            env:
              MEILI_NO_ANALYTICS: true
            envFrom:
              - secret: hoarder-secret

    service:
      web:
        controller: web
        ports:
          http:
            port: 3000
      chrome:
        controller: chrome
        ports:
          http:
            port: 9222
      meilisearch:
        controller: meilisearch
        ports:
          http:
            port: 7700

    ingress:
      main:
        className: internal
        hosts:
          - host: "{{ .Release.Name }}.omux.io"
            paths:
              - path: /
                service:
                  identifier: web
                  port: http

    persistence:
      web:
        existingClaim: hoarder-data
        advancedMounts:
          web:
            web:
              - path: /data

      meilisearch:
        existingClaim: hoarder-search
        advancedMounts:
          meilisearch:
            meilisearch:
              - path: /meili_data

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.omux.io"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - port: http
                name: app
