---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app hoarder
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    timeout: 30m
  upgrade:
    timeout: 30m
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/hoarder-app/hoarder
              tag: release
            env:
              DATA_DIR: /data
              MEILI_ADDR: http://localhost:7700
              BROWSER_WEB_URL: http://localhost:9222
            envFrom:
              - secretRef:
                  name: &secret hoarder-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 3000
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
          chrome:
            image:
              repository: gcr.io/zenika-hub/alpine-chrome
              tag: "124"
            args:
              - chromium-browser
              - --headless
              - --no-sandbox
              - --disable-gpu
              - --disable-dev-shm-usage
              - --remote-debugging-address=0.0.0.0
              - --remote-debugging-port=9222
              - --hide-scrollbars
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
          search:
            image:
              repository: getmeili/meilisearch
              tag: v1.11.1
            env:
              MEILI_NO_ANALYTICS: "true"
            envFrom:
              - secretRef:
                  name: *secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      main:
        controller: main
        ports:
          http:
            port: *port
          chrome:
            port: 9222
          search:
            port: 7700

    ingress:
      main:
        className: internal
        hosts:
          - host: &host "{{ .Release.Name }}.omux.io"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http

    persistence:
      data:
        type: pvc
        existingClaim: hoarder-data
      search:
        type: pvc
        existingClaim: hoarder-search

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
