---
connectivity:
  checker:
    interval: 1m
    target: 1.1.1.1:53

endpoints:
  - conditions:
      - "[CONNECTED] == true"
    group: connectivity
    interval: 1m
    name: Cloudflare
    url: icmp://1.1.1.1

  - conditions:
      - "[CONNECTED] == true"
    group: connectivity
    interval: 1m
    name: Google
    url: icmp://8.8.8.8

  - conditions:
      - "[CONNECTED] == true"
    group: connectivity
    interval: 1m
    name: Quad9
    url: icmp://9.9.9.9

metrics: true

storage:
  caching: true
  path: ${GATUS_CONFIG_PATH}/gatus.db
  type: sqlite

ui:
  title: Status | Gatus
  header: Status
  logo: https://avatars.githubusercontent.com/u/26648418
  link: https://github.com/kyteproject
  buttons:
    - name: Github
      link: https://github.com/kyteproject
    - name: Homelab
      link: https://github.com/kyteproject/gitops-homelab

web:
  port: ${GATUS_WEB_PORT}
