---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: github
spec:
  type: github
  address: https://github.com/kyteproject/gitops-homelab
  secretRef:
    name: github-token-secret
