---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: irqbalance
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      irqbalance:
        type: daemonset
        containers:
          app:
            image:
              repository: ghcr.io/kyteproject/irqbalance
              tag: 1.9.4@sha256:1d72c39c84c8511ce5429b9d430630d9a138007d36677a8894b3a1610a3e4e14
            env:
              IRQBALANCE_BANNED_CPULIST: 12-19 # 12-19 are E-cores
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 32Mi
            securityContext:
              privileged: true
    defaultPodOptions:
      hostIPC: true
      hostPID: true
    persistence:
      run:
        type: emptyDir
        globalMounts:
          - path: /run/irqbalance
