---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vikunja
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: vikunja-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        INIT_POSTGRES_DBNAME: vikunja
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .VIKUNJA_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .VIKUNJA_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

        VIKUNJA_DATABASE_HOST: postgres-rw.database.svc.cluster.local
        VIKUNJA_DATABASE_TYPE: postgres
        VIKUNJA_DATABASE_USER: "{{ .VIKUNJA_POSTGRES_USER }}"
        VIKUNJA_DATABASE_PASSWORD: "{{ .VIKUNJA_POSTGRES_PASS }}"
        VIKUNJA_DATABASE_DATABASE: vikunja

        VIKUNJA_CACHE_TYPE: redis
        VIKUNJA_REDIS_HOST: dragonfly.database.svc.cluster.local:6379

        VIKUNJA_MAILER_HOST: "{{ .SMTP_RELAY_HOST }}"
        VIKUNJA_MAILER_PORT: "{{ .SMTP_RELAY_PORT }}"
        VIKUNJA_MAILER_USERNAME: "{{ .SMTP_RELAY_USERNAME }}"
        VIKUNJA_MAILER_PASSWORD: "{{ .SMTP_RELAY_PASSWORD }}"
        VIKUNJA_MAILER_FROMEMAIL: "Vikunja <vikunja@omux.io>"

        VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHENTIK_AUTHURL: "{{ .AUTHENTIK_AUTH_URL }}"
        VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHENTIK_CLIENTID: "{{ .AUTHENTIK_CLIENT_ID }}"
        VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHENTIK_CLIENTSECRET: "{{ .AUTHENTIK_CLIENT_SECRET }}"

  dataFrom:
    - extract:
        key: vikunja
    - extract:
        key: cloudnative-pg
    - extract:
        key: smtp-relay
