---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app vikunja
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      vikunja:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/kyteproject/postgres-init
              tag: 17.6
              pullPolicy: IfNotPresent
            envFrom: &envFrom
              - secretRef:
                  name: vikunja-secret
        containers:
          app:
            image:
              repository: vikunja/vikunja
              tag: unstable@sha256:0801dd464af4d85744a732a81bef9a973f01d3bfcd4ea62c9e150f069fc5ff10
            env:
              VIKUNJA_REDIS_ENABLED: "1"
              VIKUNJA_CACHE_ENABLED: "1"
              VIKUNJA_MAILER_ENABLED: "true"
              VIKUNJA_SERVICE_PUBLICURL: "https://vikunja.omux.io"
              VIKUNJA_SERVICE_ENABLECALDAV: "true"
              VIKUNJA_SERVICE_INTERFACE: ":3456"
              VIKUNJA_SERVICE_TIMEZONE: Europe/London
              TZ: Europe/London
            envFrom: *envFrom
            resources:
              requests:
                cpu: 25m
                memory: 128Mi
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
    persistence:
      config:
        type: configMap
        name: vikunja-configmap
        globalMounts:
          - path: /app/vikunja/config.yml
            subPath: config.yml
            readOnly: true
      files:
        existingClaim: *app
        advancedMounts:
          vikunja:
            app:
              - path: /app/vikunja/files
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.omux.io"
          - tasks.omux.io
          - vik.omux.io
        parentRefs:
          - name: envoy-internal
            namespace: networking
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: &port 3456
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
