apiVersion: v1
kind: Pod
metadata:
  name: qbittorrent-debug
  namespace: media
spec:
  containers:
  - name: debug
    image: alpine
    command: ['/bin/sh', '-c', 'sleep 3600']
    volumeMounts:
    - name: config
      mountPath: /config
  volumes:
  - name: config
    persistentVolumeClaim:
      claimName: qbittorrent
