---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: &name qbittorrent
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 2Gi
  storageClassName: ceph-filesystem
