---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app qbittorrent
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      qbittorrent:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/qbittorrent
              tag: 5.0.4@sha256:995c561247b069c10b1fa098186f35b3155c2df63912041f70637a9232755756
            env:
              QBT_WEBUI_PORT: &port 8080
              QBT_TORRENTING_PORT: &torrentPort 50413
              TZ: Europe/London
              QBT_DEBUG: true
              QBT_TRACE: true
              QBT_LOG_LEVEL: DEBUG
            # probes:
            #   liveness: &probes
            #     enabled: true
            #     custom: true
            #     spec:
            #       httpGet:
            #         path: /api/v2/app/version
            #         port: *port
            #       initialDelaySeconds: 0
            #       periodSeconds: 10
            #       timeoutSeconds: 1
            #       failureThreshold: 3
            #   readiness: *probes
            #   startup:
            #     enabled: true
            #     spec:
            #       failureThreshold: 30
            #       periodSeconds: 10
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 8Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: ["ALL"]
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [65536, 65537, 65538, 10000]
    persistence:
      # config:
      #   existingClaim: *app
      config:
        type: emptyDir
      # media:
      #   type: nfs
      #   server: tank.lan
      #   path: /mnt/tank/Media/torrents
      #   globalMounts:
      #     - path: /torrents
      #       subPath: .
      tmp:
        type: emptyDir
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.omux.io"
          - qb.omux.io
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
    service:
      app:
        controller: *app
        nameOverride: *app
        ports:
          http:
            port: *port
      bittorrent:
        controller: *app
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 192.168.20.82, ::ffff:192.168.20.82
        ports:
          bittorrent-tcp:
            port: *torrentPort
            protocol: TCP
