---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: maloja
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: maloja-secret
    template:
      data:
        MALOJA_FORCE_PASSWORD: "{{ .MALOJA_FORCE_PASSWORD }}"
  dataFrom:
    - extract:
        key: maloja
