---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: maloja
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 1h
  values:
    controllers:
      maloja:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/krateng/maloja
              tag: 3.2.4@sha256:4ecea26058d2ca5168a8d53820279942d28f0606664cea6425f42371d5d88f95
            env:
              TZ: &tz Europe/London
              MALOJA_LOCATION_TIMEZONE: *tz
              # MALOJA_PORT: &port 8080
              MALOJA_DATA_DIRECTORY: /data
              # MALOJA_DIRECTORY_CONFIG: /data/config
              # MALOJA_DIRECTORY_STATE: /data/state
              # MALOJA_DIRECTORY_CACHE: /data/cache
              # MALOJA_DIRECTORY_LOGS: /data/logs
              # MALOJA_DIRECTORY_IMAGES: /data/images
              # MALOJA_LOGGING: false
              # MALOJA_SKIP_SETUP: "true"
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - subPath: data
            path: /data
      tmpfs:
        type: emptyDir
        advancedMounts:
          maloja:
            app:
              - path: /tmp
                subPath: tmp
              - path: /run
                subPath: run
              - path: /var/run
                subPath: var-run
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.omux.io"
        parentRefs:
          - name: envoy-internal
            namespace: networking
            sectionName: https
    service:
      app:
        ports:
          http:
            port: 42010
