---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: thelounge
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: thelounge-secret
    creationPolicy: Owner
    template:
      data:
        config.js: |
          "use strict";
          module.exports = {
            public: false,
            host: undefined,
            port: 9000,
            bind: undefined,
            reverseProxy: false,
            maxHistory: 10000,
            https: {
              enable: false,
              key: "",
              certificate: "",
              ca: "",
            },
            theme: "default",
            prefetch: false,
            disableMediaPreview: false,
            prefetchStorage: false,
            prefetchMaxImageSize: 2048,
            prefetchMaxSearchSize: 50,
            prefetchTimeout: 5000,
            fileUpload: {
              enable: false,
              maxFileSize: 10240,
              baseUrl: null,
            },
            transports: ["polling", "websocket"],
            leaveMessage: null,
            defaults: {
              name: "Libera.Chat",
              host: "irc.libera.chat",
              port: 6697,
              password: "",
              tls: true,
              rejectUnauthorized: true,
              nick: "thelounge%%",
              username: "thelounge",
              realname: "",
              join: "#thelounge",
              leaveMessage: "",
            },
            lockNetwork: false,
            messageStorage: ["sqlite", "text"],
            useHexIp: false,
            webirc: null,
            identd: {
              enable: false,
              port: 113,
            },
            oidentd: null,
            ldap: null,
            debug: {
              ircFramework: false,
              raw: false,
            },
          };
  dataFrom:
    - extract:
        key: thelounge