---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
configMapGenerator:
  - name: glance-configmap
    files:
      - glance.yml=./config/glance.yml
generatorOptions:
  disableNameSuffixHash: true
