---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: erpnext
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: erpnext-secret
    creationPolicy: Owner
    template:
      data:
        ERPNEXT_DB_ROOT_PASSWORD: "{{ .ERPNEXT_DB_ROOT_PASSWORD }}"
        ERPNEXT_DB_PASSWORD: "{{ .ERPNEXT_DB_PASSWORD }}"
        ERPNEXT_REDIS_PASSWORD: "{{ .ERPNEXT_REDIS_PASSWORD }}"
        ERPNEXT_ADMIN_PASSWORD: "{{ .ERPNEXT_ADMIN_PASSWORD }}"
        SECRET_DOMAIN: "{{ .SECRET_DOMAIN }}"
  dataFrom:
    - extract:
        key: erpnext
