---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bookstack
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: bookstack-secret
    creationPolicy: Owner
    template:
      data:
        DB_PASSWORD: "{{ .BOOKSTACK_MARIADB_PASSWORD }}"
        DB_DATABASE: "{{ .BOOKSTACK_MARIADB_DB }}"
        DB_USERNAME: "{{ .BOOKSTACK_MARIADB_USER }}"
        DB_HOST: "{{ .BOOKSTACK_MARIADB_HOST }}"
  dataFrom:
    - extract:
        key: bookstack
