---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bookstack
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: bookstack-secret
    creationPolicy: Owner
    template:
      data:
        DB_HOST: "{{ .BOOKSTACK_MARIADB_HOST }}"
        DB_PORT: "3306"
        DB_USERNAME: "{{ .BOOKSTACK_MARIADB_USER }}"
        DB_PASSWORD: "{{ .BOOKSTACK_MARIADB_PASSWORD }}"
        DB_DATABASE: "{{ .BOOKSTACK_MARIADB_DB }}"

        AUTH_METHOD: "standard"
        AUTH_AUTO_INITIATE: "false"
        OIDC_NAME: "authentik"
        OIDC_DISPLAY_NAME_CLAIMS: "name"
        OIDC_CLIENT_ID: "{{ .BOOKSTACK_AUTH_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .BOOKSTACK_AUTH_CLIENT_SECRET }}"
        OIDC_ISSUER: "https://id.omux.io/application/o/bookstack/"
        OIDC_ISSUER_DISCOVER: "true"
        OIDC_END_SESSION_ENDPOINT: "https://id.omux.io/application/o/bookstack/end-session/"

        MAIL_DRIVER: "smtp"
        MAIL_FROM: "bookstack@omux.io"
        MAIL_FROM_NAME: "BookStack"
  dataFrom:
    - extract:
        key: bookstack
