---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bookstack
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: bookstack-secret
    creationPolicy: Owner
    template:
      data:
        DB_HOST: "{{ .BOOKSTACK_MARIADB_HOST }}"
        DB_PORT: "3306"
        DB_USERNAME: "{{ .BOOKSTACK_MARIADB_USER }}"
        DB_PASSWORD: "{{ .BOOKSTACK_MARIADB_PASSWORD }}"
        DB_DATABASE: "{{ .BOOKSTACK_MARIADB_DB }}"

        MAIL_DRIVER: "smtp"
        MAIL_FROM: "bookstack@omux.io"
        MAIL_FROM_NAME: "BookStack"
  dataFrom:
    - extract:
        key: bookstack
