---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app bookstack
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      bookstack:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/linuxserver/bookstack
              tag: v24.05.4-ls166
            env:
              TZ: Europe/London
              PUID: 1000
              PGID: 1000
              APP_URL: https://docs.omux.io
            envFrom:
              - secretRef:
                  name: bookstack-secret
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
              limits:
                memory: 256Mi
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.omux.io"
          - docs.omux.io
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: &port 80
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /config
    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - port: http