---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: changedetection
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: changedetection-secret
    creationPolicy: Owner
    template:
      data:
        WEBDRIVER_API_KEY: "{{ .WEBDRIVER_API_KEY }}"
  dataFrom:
    - extract:
        key: changedetection
