---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app changedetection
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      changedetection:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/dgtlmoon/changedetection.io
              tag: 0.49.4
              pullPolicy: IfNotPresent
            env:
              TZ: Europe/London
              PORT: &port 5000
              USE_X_SETTINGS: 1
              PLAYWRIGHT_DRIVER_URL: ws://localhost:3000/?stealth=1&--disable-web-security=true&--user-data-dir=~/browserless-cache-123
            envFrom:
              - secretRef:
                  name: changedetection-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
          browser:
            image:
              repository: docker.io/browserless/chrome
              tag: latest
              pullPolicy: IfNotPresent
            env:
              - { name: SCREEN_WIDTH, value: "1920" }
              - { name: SCREEN_HEIGHT, value: "1024" }
              - { name: SCREEN_DEPTH, value: "16" }
              - { name: ENABLE_DEBUGGER, value: "false" }
              - { name: PREBOOT_CHROME, value: "true" }
              - { name: CONNECTION_TIMEOUT, value: "300000" }
              - { name: MAX_CONCURRENT_SESSIONS, value: "10" }
              - { name: CHROME_REFRESH_TIME, value: "600000" }
              - { name: DEFAULT_BLOCK_ADS, value: "true" }
              - { name: DEFAULT_STEALTH, value: "true" }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        existingClaim: *app
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.omux.io"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port