---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: changedetection
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 1h
  values:
    controllers:
      changedetection:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/dgtlmoon/changedetection.io
              tag: 0.50.34@sha256:d00e8ec017748a9ed5f6ea3f6a02d52eef1594d175b2ba04f361848fc85c6e06
              pullPolicy: IfNotPresent
            env:
              TZ: Europe/London
              PORT: &port 5000
              USE_X_SETTINGS: 1
              PLAYWRIGHT_DRIVER_URL: ws://localhost:3000/?stealth=1&--disable-web-security=true&--user-data-dir=~/browserless-cache-123
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
          browser:
            image:
              repository: docker.io/browserless/chrome
              tag: latest@sha256:57d19e414d9fe4ae9d2ab12ba768c97f38d51246c5b31af55a009205c136012f
              pullPolicy: IfNotPresent
            env:
              - { name: SCREEN_WIDTH, value: "1920" }
              - { name: SCREEN_HEIGHT, value: "1024" }
              - { name: SCREEN_DEPTH, value: "16" }
              - { name: ENABLE_DEBUGGER, value: "false" }
              - { name: PREBOOT_CHROME, value: "true" }
              - { name: CONNECTION_TIMEOUT, value: "300000" }
              - { name: MAX_CONCURRENT_SESSIONS, value: "10" }
              - { name: CHROME_REFRESH_TIME, value: "600000" }
              - { name: DEFAULT_BLOCK_ADS, value: "true" }
              - { name: DEFAULT_STEALTH, value: "true" }
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        advancedMounts:
          changedetection:
            app:
              - path: /datastore
            browser:
              - path: /tmp
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.omux.io"
        parentRefs:
          - name: envoy-internal
            namespace: networking
            sectionName: https
    service:
      app:
        ports:
          http:
            port: *port
