---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
data:
  settings.yaml: |
    title: Homelab
    favicon: https://github.com/walkxcode/dashboard-icons/blob/main/png/heimdall.png
    theme: dark
    color: slate
    headerStyle: clean
    statusStyle: dot
    useEqualHeights: false
    fiveColumns: true
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      showSearchSuggestions: true
      hideVisitURL: true
    layout:
      Administration:
        style: column
        icon: mdi-network
      Cluster:
        style: column
        icon: synology.png
      Media:
        style: column
        icon: mdi-download-circle
      Home:
        style: column
        icon: home-assistant
      Tools:
        style: column
        icon: mdi-tools

  widgets.yaml: |
    - search:
        provider: [google]
        focus: false
        target: _blank
    - kubernetes:
        cluster:
          cpu: true
          memory: true
          show: true
          showLabel: true
        nodes:
          cpu: true
          memory: true
          show: false
          showLabel: true
    - openmeteo:
        label: Home
        latitude: {{HOMEPAGE_VAR_LATITUDE}}
        longitude: {{HOMEPAGE_VAR_LONGITUDE}}
        units: metric
        cache: 5
    - datetime:
        text_size: l
        format:
          timeStyle: short
          dateStyle: short
          hourCycle: h23
    - unifi_console:
        url: {{HOMEPAGE_VAR_UNIFI_URL}}
        username: {{HOMEPAGE_VAR_UNIFI_USERNAME}}
        password: {{HOMEPAGE_VAR_UNIFI_PASSWORD}}

  services.yaml: |
    - Administration:
        - DMARC Reports:
            href: https://dmarc-report.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            siteMonitor: https://dmarc-report.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            icon: mail-in-a-box.png
        - Echo Server:
            href: https://echo-server.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            siteMonitor: https://echo-server.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            icon: babybuddy.png
        - Who Am I:
            href: https://whoami.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            siteMonitor: https://whoami.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            icon: ward.png
        - Cloudflared:
            href: https://dash.cloudflare.com/
            icon: cloudflare-zero-trust.png
            description: Cloudflared Tunnel Status
            # widget:
            #   type: cloudflared
            #   accountid: {{HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID}}
            #   tunnelid: {{HOMEPAGE_VAR_CLOUDFLARED_TUNNELID}}
            #   key: {{HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN}}
            #   fields: ["status"]
    - Cluster:
        - Monitoring:
            - Grafana:
                href: https://grafana.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
                siteMonitor: https://grafana.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
                icon: grafana.png
                # widget:
                #   type: grafana
                #   url: http://grafana.monitoring.svc.cluster.local:3000
                #   username: https://grafana.{{HOMEPAGE_VAR_GRAFANA_USERNAME}}
                #   password: https://grafana.{{HOMEPAGE_VAR_GRAFANA_PASSWORD}}
            - Alert Manager:
                href: https://am.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
                siteMonitor: https://am.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
                icon: alertmanager.png
            - Prometheus:
                href: https://prometheus.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}/alerts?state=pending&state=firing&showEmptyGroups=0
                siteMonitor: https://prometheus.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}/alerts?state=pending&state=firing&showEmptyGroups=0
                icon: prometheus.png
            - Gatus (Gateway):
                href: https://gatus.{{HOMEPAGE_VAR_SECRET_TECH_DOMAIN_NAME}}:8443
                siteMonitor: https://gatus.{{HOMEPAGE_VAR_SECRET_TECH_DOMAIN_NAME}}:8443
                icon: gatus.png
            - Gatus (Cluster):
                href: https://status.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
                siteMonitor: https://status.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
                icon: gatus.png
            - Karma:
                href: https://karma.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
                siteMonitor: https://karma.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
                icon: karma.png
        - Storage:
            - TrueNAS:
                href: https://ragnar.{{HOMEPAGE_VAR_SECRET_TECH_DOMAIN_NAME}}
                siteMonitor: https://ragnar.{{HOMEPAGE_VAR_SECRET_TECH_DOMAIN_NAME}}
                icon: truenas.png
            - Rook:
                href: https://rook.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
                siteMonitor: https://rook.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
                icon: rook.png
            - EMQX:
                href: https://emqx.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
                siteMonitor: https://emqx.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
                icon: emqx.
            - PostgreSQL:
                href: https://pgadmin.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
                siteMonitor: https://pgadmin.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
                icon: pgadmin.png
            - Dragonfly:
                href: https://dragonfly.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
                siteMonitor: https://dragonfly.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
                icon: dragonfly.png

    - Media:
        - Overseerr:
            href: https://overseerr.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            siteMonitor: https://overseerr.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            icon: overseerr.png
            description: Media Requests
            widget:
              type: overseerr
              url: http://overseerr.media.svc.cluster.local
              key: {{HOMEPAGE_VAR_OVERSEERR_TOKEN}}
        - Plex:
            href: https://plex.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            siteMonitor: https://plex.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            icon: plex.png
            description: Media Server
            widget:
              type: plex
              url: https://plex.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
              key: {{HOMEPAGE_VAR_PLEX_TOKEN}}
        - Sonarr:
            href: https://sonarr.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            siteMonitor: https://sonarr.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            icon: sonarr.png
            description: TV Shows
            widget:
              type: sonarr
              url: http://sonarr.media.svc.cluster.local:8989
              key: {{HOMEPAGE_VAR_SONARR_TOKEN}}
        - Radarr-4k:
            href: https://radarr-4k.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            siteMonitor: https://radarr-4k.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            icon: radarr.png
            description: 4K Movies
            widget:
              type: radarr
              url: http://radarr-4k.media.svc.cluster.local:7878
              key: {{HOMEPAGE_VAR_RADARR_4K_TOKEN}}
        - Radarr:
            href: https://radarr.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            siteMonitor: https://radarr.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            icon: radarr.png
            description: Movies
            widget:
              type: radarr
              url: http://radarr.media.svc.cluster.local:7878
              key: {{HOMEPAGE_VAR_RADARR_TOKEN}}
        - Lidarr:
            href: https://lidarr.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            siteMonitor: https://lidarr.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            icon: lidarr.png
            description: Music
            widget:
              type: lidarr
              url: http://lidarr.media.svc.cluster.local:8686
              key: {{HOMEPAGE_VAR_LIDARR_TOKEN}}
        - Sabnzbd:
            href: https://sabnzbd.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            siteMonitor: https://sabnzbd.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            icon: sabnzbd.png
            description: NZB Downloader
            widget:
              type: sabnzbd
              url: http://sabnzbd.media.svc.cluster.local:8080
              key: {{HOMEPAGE_VAR_SABNZBD_TOKEN}}
        - qBitTorrent:
            href: https://qbittorrent.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            siteMonitor: https://qbittorrent.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            icon: qbittorrent.png
            description: Torrent Downloader
            widget:
              type: qbittorrent
              url: https://qbittorrent.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
              username: {{HOMEPAGE_VAR_QBITTORRENT_USERNAME}}
              password: {{HOMEPAGE_VAR_QBITTORRENT_PASSWORD}}
    - Home:
        - Home Assistant:
            href: https://home.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            siteMonitor: https://home.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            icon: home-assistant.png
        - Node Red:
            href: https://node-red.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            siteMonitor: https://node-red.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            icon: node-red.png
        - Wiki Recipes:
            href: https://wiki.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}/recipes/index
            siteMonitor: https://wiki.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}/recipes/index
            icon: wikijs.png
        - Shlink:
            href: https://shlink.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            siteMonitor: https://shlink.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            icon: shlink.png
        - Octoprint:
            href: https://octopi.{{HOMEPAGE_VAR_SECRET_TECH_DOMAIN_NAME}}
            siteMonitor: https://octopi.{{HOMEPAGE_VAR_SECRET_TECH_DOMAIN_NAME}}
            icon: octoprint.png
        - Stirling PDF:
            href: https://pdf-tool.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            siteMonitor: https://pdf-tool.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            icon: https://raw.githubusercontent.com/Stirling-Tools/Stirling-PDF/main/docs/stirling.png
        - Home Code:
            href: https://ha-code.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            siteMonitor: https://ha-code.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            icon: home-assistant.png
        - Dashy Code:
            href: https://dashy-code.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            siteMonitor: https://dashy-code.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            icon: etcd.png
    - Tools:
        - Atuin:
            href: https://atuin.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            siteMonitor: https://atuin.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            icon: atuin.png
        - Change Detection:
            href: https://changedetection.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            siteMonitor: https://changedetection.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            icon: changedetection-io.png
        - ChartDB:
            href: https://chartdb.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            siteMonitor: https://chartdb.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            icon: chartdb.png
        - ERPNext:
            href: https://erpnext.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            siteMonitor: https://erpnext.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            icon: erpnext.png
        - N8n:
            href: https://n8n.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            siteMonitor: https://n8n.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            icon: n8n.png
        - Wakapi:
            href: https://wakapi.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            siteMonitor: https://wakapi.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
            icon: wakapi.png

  bookmarks.yaml: |
    - Communicate:
        - Discord:
            - icon: discord.png
              href: 'https://discord.com/app'
        - Gmail:
            - icon: gmail.png
              href: 'http://gmail.com'
        - Google Calendar:
            - icon: google-calendar.png
              href: 'https://calendar.google.com'
    - Media Links:
        - YouTube:
            - icon: youtube.png
              href: 'https://youtube.com/feed/subscriptions'
        # - Navidrome:
        #     - icon: navidrome.png
        #       href: https://music.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
        # - Spotify:
        #     - icon: spotify.png
        #       href: 'http://open.spotify.com'
    - Git:
        - kubesearch:
            - icon: kubernetes-dashboard.png
              href: 'https://kubesearch.dev/'
        - home-ops:
            - icon: github.png
              href: 'https://github.com/kyteproject/gitops-homelab'
    - Tools:
        - Excalidraw:
            - icon: excalidraw.png
              href: 'https://excalidraw.com'

  docker.yaml: ""

  kubernetes.yaml: |
    mode: cluster
