---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: trivy-operator
spec:
  groups:
    - name: trivy-operator.rules
      rules:
        - alert: TrivyOperatorAbsent
          expr: |-
            absent(up{job="trivy-operator"})
          for: 5m
          annotations:
            summary: >-
              Trivy Operator has disappeared from Prometheus service discovery
          labels:
            severity: critical

    - name: trivy-vulnerabilities.rules
      rules:
        - alert: TrivyCriticalVulnerabilities
          expr: |-
            sum by (namespace, name) (trivy_image_vulnerabilities{severity="Critical"}) > 0
          for: 15m
          annotations:
            summary: >-
              {{ $labels.name }} in {{ $labels.namespace }} has {{ $value }} critical vulnerabilities
            description: >-
              Workload {{ $labels.name }} in namespace {{ $labels.namespace }} has critical security vulnerabilities that should be addressed immediately.
          labels:
            severity: critical

        - alert: TrivyHighVulnerabilities
          expr: |-
            sum by (namespace, name) (trivy_image_vulnerabilities{severity="High"}) > 10
          for: 1h
          annotations:
            summary: >-
              {{ $labels.name }} in {{ $labels.namespace }} has {{ $value }} high vulnerabilities
            description: >-
              Workload {{ $labels.name }} in namespace {{ $labels.namespace }} has more than 10 high severity vulnerabilities.
          labels:
            severity: warning

        - alert: TrivyExposedSecrets
          expr: |-
            sum by (namespace, name) (trivy_resource_exposedsecrets) > 0
          for: 5m
          annotations:
            summary: >-
              {{ $labels.name }} in {{ $labels.namespace }} has exposed secrets
            description: >-
              Workload {{ $labels.name }} in namespace {{ $labels.namespace }} contains exposed secrets or sensitive information.
          labels:
            severity: critical

        - alert: TrivyConfigAuditFailures
          expr: |-
            sum by (namespace, name) (trivy_resource_configaudits{severity=~"CRITICAL|HIGH"}) > 5
          for: 30m
          annotations:
            summary: >-
              {{ $labels.name }} in {{ $labels.namespace }} has {{ $value }} configuration issues
            description: >-
              Workload {{ $labels.name }} in namespace {{ $labels.namespace }} has critical or high severity configuration audit failures.
          labels:
            severity: warning

