---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: authentik-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App DB
        AUTHENTIK_POSTGRESQL__NAME: &dbName authentik
        AUTHENTIK_POSTGRESQL__HOST: &dbHost postgres-rw.database.svc.cluster.local
        AUTHENTIK_POSTGRESQL__USER: &dbUser "{{ .AUTHENTIK_POSTGRESQL__USER }}"
        AUTHENTIK_POSTGRESQL__PASSWORD: &dbPass "{{ .AUTHENTIK_POSTGRESQL__PASSWORD }}"
        AUTHENTIK_REDIS__HOST: dragonfly.database.svc.cluster.local
        AUTHENTIK_REDIS__PORT: "6379"
        AUTHENTIK_REDIS__DB: "3"
        AUTHENTIK_SECRET_KEY: "{{ .AUTHENTIK_SECRET_KEY }}"

        # App Geo
        # MAXMIND_ACCOUNT_ID: "{{ .ACCOUNT_ID }}"
        # MAXMIND_LICENSE_KEY: "{{ .LICENSE_KEY }}"

        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: authentik
    # - extract:
    #     key: maxmind
    - extract:
        key: cloudnative-pg
