---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: authentik-secret
    creationPolicy: Owner
    template:
      data:
        # App DB
        AUTHENTIK_POSTGRESQL__NAME: &dbName authentik
        AUTHENTIK_POSTGRESQL__HOST: &dbHost postgres-rw.database.svc.cluster.local
        AUTHENTIK_POSTGRESQL__USER: &dbUser "{{ .AUTHENTIK_POSTGRESQL__USER }}"
        AUTHENTIK_POSTGRESQL__PASSWORD: &dbPass "{{ .AUTHENTIK_POSTGRESQL__PASSWORD }}"
        AUTHENTIK_REDIS__DB: "3"
        AUTHENTIK_SECRET_KEY: "{{ .AUTHENTIK_SECRET_KEY }}"

        AUTHENTIK_EMAIL__HOST: "{{ .SMTP_RELAY_HOST }}"
        AUTHENTIK_EMAIL__PORT: "{{ .SMTP_RELAY_PORT }}"
        AUTHENTIK_EMAIL__USERNAME: "{{ .SMTP_RELAY_USERNAME }}"
        AUTHENTIK_EMAIL__PASSWORD: "{{ .SMTP_RELAY_PASSWORD }}"
        AUTHENTIK_EMAIL__USE_SSL: "true"
        AUTHENTIK_EMAIL__FROM: "Authentik <auth@omux.io>"

        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: authentik
    # - extract:
    #     key: maxmind
    - extract:
        key: cloudnative-pg
    - extract:
        key: smtp-relay
