---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app authentik
spec:
  chart:
    spec:
      chart: authentik
      version: 2025.2.2
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  interval: 30m
  maxHistory: 3
  uninstall:
    keepHistory: false
  values:
    additionalObjects:
      apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      metadata:
        name: authentik
        namespace: security
      spec:
        hostnames:
          - authentik.omux.io
          - auth.omux.io
          - id.omux.io
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
            - name: authentik-server
              namespace: security
              port: 443
    global:
      deploymentAnnotations:
        secret.reloader.stakater.com/reload: &secret authentik-secret
      env:
        - name: AUTHENTIK_SESSION_STORAGE
          value: db
      envFrom:
        - secretRef:
            name: *secret
    server:
      replicas: 1
      initContainers:
        - name: init-db
          image: ghcr.io/kyteproject/postgres-init:17.4
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: *secret
      resources:
        requests:
          cpu: 50m
          memory: 500Mi
        limits:
          memory: 800Mi
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
    worker:
      replicas: 1
      resources:
        requests:
          cpu: 50m
          memory: 500Mi
        limits:
          memory: 1200Mi
    authentik:
      log_level: info
      redis:
        host: dragonfly.database.svc.cluster.local
      error_reporting:
        enable: false
    geoip:
      enabled: false
    prometheus:
      rules:
        enabled: true