---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 2024.12.1
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      deploymentAnnotations:
        secret.reloader.stakater.com/reload: &secret authentik-secret
      storageClass: openebs-hostpath
      env:
        - name: AUTHENTIK_SESSION_STORAGE
          value: db
      envFrom:
        - secretRef:
            name: *secret
    authentik:
      log_level: info
      redis:
        host: dragonfly.database.svc.cluster.local
      avatars: "gravatar,initials"
      email:
        host: smtp-relay.networking.svc.cluster.local
        port: 587
        from: "Access <access@omux.dev>"
      error_reporting:
        enable: false
        send_pii: false
      outposts:
        container_image_base: ghcr.io/goauthentik/%(type)s:%(version)s
      # https://github.com/goauthentik/authentik/pull/7118
      # https://github.com/goauthentik/authentik/issues/1285
    server:
      replicas: 1
      initContainers:
        - name: init-db
          image: ghcr.io/kyteproject/postgres-init:17.4
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: *secret
      resources:
        requests:
          cpu: 50m
          memory: 500Mi
        limits:
          memory: 800Mi
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
    worker:
      replicas: 1
      resources:
        requests:
          cpu: 50m
          memory: 500Mi
        limits:
          memory: 1200Mi
    geoip:
      enabled: false
    prometheus:
      rules:
        enabled: true
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.omux.io"
          - auth.omux.io
          - id.omux.io
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - port: http
                name: app
