---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - cloudflare-ddns/ks.yaml
  - cloudflared/ks.yaml
  - echo-server/ks.yaml
  - external-dns/ks.yaml
  - nginx/ks.yaml
  - smtp-relay/ks.yaml
components:
  - ../../flux/components/common
