---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cloudflare-ddns/ks.yaml
  - cloudflared/ks.yaml
  - echo-server/ks.yaml
  - external-dns/ks.yaml
  - nginx/ks.yaml
  - smtp-relay/ks.yaml
