---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: personal
resources:
  # - erpnext/ks.yaml
  - hoarder/ks.yaml
  # - immich/ks.yaml
  # - paperless/ks.yaml
components:
  - ../../../../infrastructure/flux/components/alerts
  - ../../../../infrastructure/flux/components/namespace
  - ../../../../infrastructure/flux/components/sops
