---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bookboss
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: bookboss-secret
    template:
      data:
        BOOKBOSS__ENCRYPTION_SECRET: "{{ .BOOKBOSS_ENCRYPTION_SECRET }}"
        BOOKBOSS__METADATA__HARDCOVER_API_TOKEN: "{{ .BOOKBOSS_HARDCOVER_API_TOKEN }}"
  dataFrom:
    - extract:
        key: bookboss
