---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cross-seed
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cross-seed-secret
    creationPolicy: Owner
    template:
      data:
        config.js: |
          module.exports = {
            action: "inject",
            apiKey: "{{.CROSS_SEED_API_KEY}}",
            delay: 30,
            duplicateCategories: false,
            flatLinking: false,
            includeEpisodes: true,
            includeNonVideos: true,
            includeSingleEpisodes: true,
            linkCategory: "cross-seed",
            linkDirs: [
              "/media/torrents/audiobooks",
              "/media/torrents/anime",
              "/media/torrents/books",
              "/media/torrents/games",
              "/media/torrents/movies",
              "/media/torrents/music",
              "/media/torrents/software",
              "/media/torrents/tv"
            ],
            linkType: "hardlink",
            matchMode: "strict",
            outputDir: null,
            port: Number(process.env.CROSS_SEED_PORT),
            qbittorrentUrl: "http://qbittorrent.default.svc.cluster.local",
            radarr: [
              "http://radarr.default.svc.cluster.local/?apikey={{ .RADARR_API_KEY }}"
            ],
            skipRecheck: true,
            sonarr: [
              "http://sonarr.default.svc.cluster.local/?apikey={{ .SONARR_API_KEY }}"
            ],
            torznab: [],
            useClientTorrents: true
          };
  dataFrom:
    - extract:
        key: cross-seed
    - extract:
        key: radarr
    - extract:
        key: sonarr
