---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cross-seed
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cross-seed-secret
    template:
      data:
        CROSS_SEED_API_KEY: "{{ .CROSS_SEED_API_KEY }}"
        RADARR_API_KEY: "{{ .RADARR_API_KEY }}"
        SONARR_API_KEY: "{{ .SONARR_API_KEY }}"
        PROWLARR_API_KEY: "{{ .PROWLARR_API_KEY }}"
  dataFrom:
    - extract:
        key: cross-seed
    - extract:
        key: radarr
    - extract:
        key: sonarr
    - extract:
        key: prowlarr
