---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app wakapi
  namespace: flux-system
spec:
  targetNamespace: tools
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./clusters/main/apps/tools/wakapi/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
