---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: loki
      version: 6.23.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    crds: Skip
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: Skip
    remediation:
      strategy: rollback
      retries: 3
  values:
    deploymentMode: SingleBinary
    loki:
      auth_enabled: false
      analytics:
        reporting_enabled: false
      server:
        log_level: info
      commonConfig:
        replication_factor: 1
        extraVolumes:
          - name: tsdb
            persistentVolumeClaim:
              claimName: loki-tsdb-pvc
        extraVolumeMounts:
          - name: tsdb
            mountPath: /var/loki
        storageConfig:
          tsdb_shipper:
            active_index_directory: /var/loki/index
            cache_location: /var/loki/index_cache
            cache_ttl: 24h
      compactor:
        working_directory: /var/loki/compactor/retention
        delete_request_store: filesystem
        retention_enabled: true
      ingester:
        chunk_encoding: snappy
      storage:
        type: filesystem
      rulerConfig:
        storage:
          type: local
      schemaConfig:
        configs:
          - from: "2024-04-01" # quote
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      limits_config:
        retention_period: 14d
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        size: 10Gi
    gateway:
      replicas: 0
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false
    lokiCanary:
      enabled: false
    test:
      enabled: false
    monitoring:
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
    sidecar:
      image:
        repository: ghcr.io/kiwigrid/k8s-sidecar
      enableUniqueFilenames: true
      rules:
        searchNamespace: ALL
        folder: /rules/fake
