---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./release.yaml
  # - ./scaledobject.yaml  # Disabled until firewall allows pod network access to zigbee controller
