---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./release.yaml
configMapGenerator:
  - name: smtp-relay-configmap
    files:
      - ./resources/maddy.conf
generatorOptions:
  disableNameSuffixHash: true
