---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - externalsecret.yaml
  - release.yaml
  - networkpolicy.yaml
configMapGenerator:
  - name: smtp-relay-configmap
    files:
      - config/maddy.conf
generatorOptions:
  disableNameSuffixHash: true
