---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app smtp-relay
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      smtp-relay:
        replicas: 2
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/kyteproject/maddy
              tag: 0.8.1@sha256:c228551b29bb8c23e754333d9e8e545ba3a2bd07e26cb86f1c788a0d7013196e
            env:
              MADDY_LOG_TARGET: stderr
              MADDY_LOG_DEBUG: "false"
              MADDY_LOG_JSON: "true"
              SMTP_RELAY_METRICS_PORT: &metricsPort 8080
              SMTP_RELAY_SMTP_PORT: &smtpPort 587
              SMTP_RELAY_SERVER_PORT: 465
            envFrom:
              - secretRef:
                  name: smtp-relay-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 64Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
    persistence:
      cache:
        type: emptyDir
        medium: Memory
      config:
        type: configMap
        name: smtp-relay-configmap
        globalMounts:
          - path: /data/maddy.conf
            subPath: maddy.conf
            readOnly: true
    service:
      app:
        controller: *app
        ports:
          http:
            port: *metricsPort
          smtp:
            port: *smtpPort
    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - port: http
