apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:OgC4nf5x9/Q7Q8k=,iv:qCoCWTUBuJF8BFsn5KE+yidXHvX7itL/D5dTx1VOquw=,tag:H+am9P+tj9t6d9Y3qI/FLw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:A8/Fex46JaMFKYSp,iv:t9FdP908904wYv1fleYpCs5KWq8dWUcxzGSKmUas4wk=,tag:rjG/1KiUyF9fd7l2lQTqZA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j05ehe53s6a3zmdgqqvj7g6hm42g0h56ga4vxsr4u52kjpagrefqnaa87c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZkZDT2grRHBWVmZnbTFa
            R2owWUJCeTlLY1BDdVZGbE9WcFhsS21BYjBnCitRc2VqK0RHclczb3U3N2I2QllI
            bFNYV0tPcWExbVZHc0VlOHVUUjdSVzgKLS0tIERMaUxkTi8rQnhuRFBjOHZ6dUtz
            SjRQQ0x6YnhQcGNDampvY2RtbUUzdTQKjg5k3KztYvWKl7bFwCuz+TncmQdNXt0X
            pzwgB/To0CzgG7PYtyGnrxwqPSSIVFXNDGa8o+aTEBdgq1XsokLJcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-28T22:05:47Z"
    mac: ENC[AES256_GCM,data:8Uwj4YNq+CDB5gTlNrXr2fgGTGCs50dsn8DB147/Vx0lUaz07cmDL7YpVsuBzvnejkmI+wr5FGbvZ0KpW7+b4HIdWVjlmuRYk/VcmA+a3M+x3YQ3NmOj8OIW7qvj2dc/rSYoGLJDD+8O1iQDcCpT+l3gknl9Wl/fvBWockUsadA=,iv:MUxj+sbNoofBGiIeYvgO88M7F8yXSV2dGIXqgHD95wo=,tag:RiFDKpIaWuGS/46Dpc0SEw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.1
