---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app mariadb
  namespace: &namespace database
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../flux/components/volsync
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: onepassword
      namespace: external-secrets
    - name: volsync
      namespace: storage
  interval: 1h
  path: ./infrastructure/controllers/database/mariadb/app
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 8Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false # no flux ks dependents
