# Cluster-level Kustomizations
# Points to apps/core
---
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: sources
    - name: monitoring
  path: ./apps/core
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-homelab
  wait: true
  timeout: 5m
