---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: sources
  path: ./apps/core/cilium/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-homelab
  wait: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium-config
  namespace: flux-system
spec:
  dependsOn:
    - name: cilium
  path: ./apps/core/cilium/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-homelab
  wait: false
  timeout: 5m
