---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubelet-csr-approver
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: coredns
  path: ./apps/core/kubelet-csr-approver/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-homelab
  wait: true
  timeout: 5m
