---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ../monitoring/prometheus-operator-crds/app
  - cilium/app
  - cilium/config
  - coredns/app
  - kubelet-csr-approver/app
  - spegel/app
