---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - home-assistant/ks.yaml
  # - zigbee2mqtt/ks.yaml
components:
  - ../../../../infrastructure/flux/components/common
