---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alertmanager-silencer
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      alertmanager-silencer:
        type: cronjob
        cronjob:
          schedule: "@daily"
          timeZone: Europe/London
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/kubanetics
              tag: 2025.3.2@sha256:309a7587c2aa7ce6a99812a61c5024240a21b708f94802a09105c61513572164
            env:
              SCRIPT_NAME: alertmanager-silencer.sh
              ALERTMANAGER_URL: http://alertmanager-operated.monitoring.svc.cluster.local:9093
              MATCHERS_0: alertname=CephNodeInconsistentMTU
              MATCHERS_1: alertname=CephNodeNetworkPacketErrors
              MATCHERS_2: alertname=CephMonClockSkew
              MATCHERS_3: alertname=CephNodeNetworkPacketDrops
              MATCHERS_4: alertname=CephNodeDiskspaceWarning
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
