---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - externalsecret.yaml
  - truenas-cert-sync.yaml
configMapGenerator:
  - name: truenas-cert-sync-script
    files:
      - scripts/sync-truenas-cert.sh
