apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync-truenas-cert
  namespace: cert-manager
spec:
  schedule: "0 */12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: cert-sync
          # Can't use bitnami on its own due to missing curl
          # https://github.com/bitnami/containers/issues/48638#issuecomment-2105357029
          initContainers:
            - name: copy-kubectl
              image: bitnami/kubectl:1.30.0-debian-12-r3
              command:
                - "/bin/sh"
                - "-c"
              args:
                - |
                  echo "copying 'kubectl' binary to shared volume...";
                  cp -f "$(which kubectl)" /shared-bin/kubectl;
              volumeMounts:
                - name: shared-bin
                  mountPath: "/shared-bin/"
          containers:
          - name: cert-sync
            image: bitnami/os-shell:12-debian-12-r20
            command:
              - "/bin/bash"
              - "-c"
              - |
                TOKEN=$(cat /var/run/secrets/kubernetes.io/truenas/token)

                if [ -z "$TOKEN" ]; then
                  echo "Error: Token is empty"
                  exit 1
                fi

                echo "Token from file exists: [YES]"
                echo "Token from file length: ${#TOKEN}"

                /scripts/sync-truenas-cert.sh "$TOKEN"
            env:
            - name: TRUENAS_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: truenas-api-token
                  key: token
            volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: shared-bin
              mountPath: "/usr/local/bin/kubectl"
              subPath: "kubectl"
            - name: truenas-token
              mountPath: "/var/run/secrets/kubernetes.io/truenas"
              readOnly: true
          volumes:
          - name: scripts
            configMap:
              name: sync-truenas-cert-script
              defaultMode: 0755
          - name: shared-bin
            emptyDir: {}
          restartPolicy: OnFailure
