---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hoarder
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: hoarder-secret
    creationPolicy: Owner
    template:
      data:
        OPENAI_API_KEY: "{{ .OPENAI_API_KEY }}"
        MEILI_MASTER_KEY: "{{ .MEILI_MASTER_KEY }}"
        NEXTAUTH_SECRET: "{{ .NEXTAUTH_SECRET }}"
        NEXT_PUBLIC_SECRET: "{{ .NEXT_PUBLIC_SECRET }}"
        OAUTH_CLIENT_ID: "{{ .OIDC_CLIENT_ID }}"
        OAUTH_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: hoarder
    - extract:
        key: openai
