---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name homepage-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name

    deletionPolicy: Delete
    template:
      data:
        HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: "{{ .CLOUDFLARE_ACCOUNT_ID }}"
        HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: "{{ .CLOUDFLARE_TUNNEL_ID }}"
        HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: "{{ .CLOUDFLARE_API_TOKEN }}"
        HOMEPAGE_VAR_UNIFI_URL: "{{ .UNIFI_URL }}"
        HOMEPAGE_VAR_UNIFI_USERNAME: "{{ .UNPOLLER_USER }}"
        HOMEPAGE_VAR_UNIFI_PASSWORD: "{{ .UNPOLLER_PASS }}"
        HOMEPAGE_VAR_MADDY: "{{ .SMTP_RELAY_HOST }}"
        HOMEPAGE_VAR_GRAFANA_USERNAME: "{{ .GRAFANA_ADMIN_USER }}"
        HOMEPAGE_VAR_GRAFANA_PASSWORD: "{{ .GRAFANA_ADMIN_PASS }}"
        HOMEPAGE_VAR_SECRET_DOMAIN_NAME: "omux.io"
  dataFrom:
    - extract:
        key: cloudflare
    - extract:
        key: smtp-relay
    - extract:
        key: grafana
    - extract:
        key: unifi
