---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      main:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v1.8.0@sha256:7dc099d5c6ec7fc945d858218565925b01ff8a60bcbfda990fc680a8b5cd0b6e
            env:
              HOMEPAGE_ALLOWED_HOSTS: &host "{{ .Release.Name }}.omux.io"
              TZ: Europe/London
            envFrom:
              - secretRef:
                  name: homepage-secret
            resources:
              requests:
                cpu: 15m
                memory: 200M
              limits:
                memory: 2G
    service:
      main:
        controller: main
        ports:
          http:
            port: &port 3000
    route:
      internal:
        hostnames: [*host]
        parentRefs:
          - name: envoy-internal
            namespace: networking
        rules:
          - backendRefs:
              - name: main
                port: *port
    persistence:
      config:
        type: configMap
        name: homepage-config
        globalMounts:
          - subPath: bookmarks.yaml
            path: /app/config/bookmarks.yaml
          - subPath: docker.yaml
            path: /app/config/docker.yaml
          - subPath: kubernetes.yaml
            path: /app/config/kubernetes.yaml
          - subPath: services.yaml
            path: /app/config/services.yaml
          - subPath: settings.yaml
            path: /app/config/settings.yaml
          - subPath: widgets.yaml
            path: /app/config/widgets.yaml
    serviceAccount:
      create: true
      name: homepage
