---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app democratic-csi-nfs
  namespace: flux-system
spec:
  path: ./infrastructure/controllers/storage/democratic-csi/nfs
  targetNamespace: storage
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: true
  dependsOn:
    - name: external-secrets-stores
    - name: snapshot-controller
  interval: 10m
