apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: system-controllers
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
namespace: kube-system
resources:
  - cilium
  - coredns
  - descheduler
  - intel-device-plugin
  - kubelet-csr-approver
  - metrics-server
  - reloader
  - spegel
