---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app system-upgrade-controller
  namespace: flux-system
spec:
  targetNamespace: system-upgrade
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./infrastructure/controllers/system-upgrade/system-upgrade-controller/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app system-upgrade-controller-plans
  namespace: flux-system
spec:
  targetNamespace: system-upgrade
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: node-feature-discovery-features
    - name: system-upgrade-controller
  path: ./infrastructure/controllers/system-upgrade/system-upgrade-controller/plans
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      TALOS_SCHEMATIC_ID: 2429a38dd7dd15e11e25b676ce491a89680a72a6fadfa1586e6ec629ae03de8b
      TALOS_VERSION: v1.9.1
      KUBERNETES_VERSION: v1.32.0
