---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app system-upgrade-controller
  namespace: &namespace system-upgrade
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  path: ./infrastructure/controllers/system-upgrade/system-upgrade-controller/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app system-upgrade-controller-plans
  namespace: &namespace system-upgrade
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: system-upgrade-controller
      namespace: *namespace
  interval: 30m
  path: ./infrastructure/controllers/system-upgrade/system-upgrade-controller/plans
  postBuild:
    substitute:
      TALOS_SCHEMATIC_ID: 868330459bde49d152c0b513725fca359f8688b3837e4d9995bcca1acef34b8e
      # renovate: depName=ghcr.io/siderolabs/installer datasource=docker
      TALOS_VERSION: v1.9.5
      # renovate: depName=ghcr.io/siderolabs/kubelet datasource=docker
      KUBERNETES_VERSION: v1.32.3
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true
