---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system-addons
  namespace: flux-system
spec:
  path: ./infrastructure/controllers/flux-system/add-ons/app
  targetNamespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: true
  interval: 10m
  dependsOn:
    - name: external-secrets-stores
