---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name immich-config-secret
  annotations:
    force-recreate: "00003"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      templateFrom:
        - configMap:
            name: immich-config-tpl
            items:
              - key: immich.config.json
  dataFrom:
    - extract:
        key: immich
    - extract:
        key: smtp-relay
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name immich-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Auth
        IMMICH_OIDC_CLIENT_ID: "{{ .IMMICH_OIDC_CLIENT_ID }}"
        IMMICH_OIDC_CLIENT_SECRET: "{{ .IMMICH_OIDC_CLIENT_SECRET }}"
        # Immich
        DB_DATABASE_NAME: &dbname immich
        DB_HOSTNAME: &dbhost postgres-immich-rw.database.svc.cluster.local
        DB_USERNAME: &dbuser "{{ .IMMICH_POSTGRES_USER }}"
        DB_PASSWORD: &dbpass "{{ .IMMICH_POSTGRES_PASS }}"
        JWT_SECRET: "{{ .IMMICH_JWT_SECRET }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: immich
    - extract:
        key: cloudnative-pg
