---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-media
  namespace: personal
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-nfs
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-cache
  namespace: personal
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-nfs
  resources:
    requests:
      storage: 50Gi  # Adjust based on thumbnail cache needs
