---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 30m
  install:
    timeout: 30m
  upgrade:
    timeout: 30m
  values:
    controllers:
      server:
        replicas: 3
        strategy: RollingUpdate
        annotations:
          secret.reloader.stakater.com/reload: "immich-secret,immich-config-secret"
          configmap.reloader.stakater.com/reload: "immich-configmap,immich-config-tpl"
        initContainers:
          02-init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16.6
              pullPolicy: Always
            envFrom:
              - secretRef:
                  name: &secret immich-secret
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: ${APP}
                  app.kubernetes.io/component: server
        containers:
          server:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.125.7
            envFrom:
              - secretRef:
                  name: *secret
              - configMapRef:
                  name: &configmap immich-configmap
            env:
              IMMICH_CONFIG_FILE: /config/immich.config.json
              IMMICH_WORKERS_INCLUDE: api
            resources:
              requests:
                gpu.intel.com/i915: 1
                cpu: 200m
                memory: 1024Mi
              limits:
                gpu.intel.com/i915: 1
                memory: 5000Mi
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/server/ping
                    port: &serverport 2283
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 5
              readiness: *probes
              startup:
                enabled: false
      microservices:
        replicas: 3
        strategy: RollingUpdate
        annotations:
          secret.reloader.stakater.com/reload: "immich-secret,immich-config-secret"
          configmap.reloader.stakater.com/reload: "immich-configmap,immich-config-tpl"
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: ${APP}
                  app.kubernetes.io/component: microservices
          nodeSelector:
            intel.feature.node.kubernetes.io/gpu: "true"
        containers:
          microservices:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.125.7
            envFrom:
              - secretRef:
                  name: *secret
              - configMapRef:
                  name: *configmap
            env:
              IMMICH_WORKERS_EXCLUDE: api
            resources:
              requests:
                gpu.intel.com/i915: 1
                cpu: 200m
                memory: 1024Mi
              limits:
                gpu.intel.com/i915: 1
                memory: 5000Mi
      machine-learning:
        replicas: 3
        strategy: RollingUpdate
        annotations:
          secret.reloader.stakater.com/reload: "immich-secret,immich-config-secret"
          configmap.reloader.stakater.com/reload: "immich-configmap,immich-config-tpl"
        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: ${APP}
                  app.kubernetes.io/component: machine-learning
        containers:
          machine-learning:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v1.125.7
            resources:
              requests:
                gpu.intel.com/i915: 1
                cpu: 200m
                memory: 1024Mi
              limits:
                gpu.intel.com/i915: 1
                memory: 5000Mi
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: &mlport 3003
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 5
              readiness: *probes
              startup:
                enabled: false

    service:
      server:
        controller: server
        ports:
          http:
            port: *serverport
          metrics:
            port: 8081
      microservices:
        controller: microservices
        ports:
          metrics:
            port: 8081
      machine-learning:
        controller: machine-learning
        ports:
          http:
            port: *mlport

    # serviceMonitor:
    #   immich:
    #     serviceName: immich-server
    #     endpoints:
    #       - port: metrics
    #         scheme: http
    #         path: /metrics
    #         interval: 1m
    #         scrapeTimeout: 30s
    #   microservices:
    #     serviceName: immich-microservices
    #     endpoints:
    #       - port: metrics
    #         scheme: http
    #         path: /metrics
    #         interval: 1m
    #         scrapeTimeout: 30s

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.omux.io"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - port: http
                name: app

    persistence:
      config:
        type: secret
        name: immich-config-secret
        advancedMounts:
          server:
            server:
              - path: /config
          microservices:
            microservices:
              - path: /config
      library:
        existingClaim: immich-media
        advancedMounts:
          server:
            server:
              - path: /usr/src/app/upload
          microservices:
            microservices:
              - path: /usr/src/app/upload
      geocoding-dump:
        type: emptyDir
        advancedMounts:
          server:
            server:
              - path: /usr/src/app/.reverse-geocoding-dump
          microservices:
            microservices:
              - path: /usr/src/app/.reverse-geocoding-dump
      geoname-dump:
        type: emptyDir
        advancedMounts:
          microservices:
            microservices:
              - path: /usr/src/app/node_modules/local-reverse-geocoder/geonames_dump
      transformers-cache:
        type: emptyDir
        advancedMounts:
          server:
            server:
              - path: /usr/src/app/.transformers_cache
          microservices:
            microservices:
              - path: /usr/src/app/.transformers_cache
      model-cache:
        type: emptyDir
        advancedMounts:
          machine-learning:
            machine-learning:
              - path: /cache
      #   # globalMounts:
      #   #   - path: /config
