---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cloudnative-pg
  namespace: flux-system
spec:
  targetNamespace: database
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: external-secrets-stores
  path: ./infrastructure/controllers/database/cloudnative-pg/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: kube-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cloudnative-pg-cluster
  namespace: flux-system
spec:
  targetNamespace: database
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: openebs
    - name: cloudnative-pg
  path: ./infrastructure/controllers/database/cloudnative-pg/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: kube-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cloudnative-pg-dashboard
  namespace: flux-system
spec:
  targetNamespace: database
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cloudnative-pg
  path: ./infrastructure/controllers/database/cloudnative-pg/dashboard
  prune: true
  sourceRef:
    kind: GitRepository
    name: kube-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
