---
name: Ansible

on:
  push:
    branches: [not-implemented]
    paths:
      - 'infrastructure/ansible/**'
  pull_request:
    paths:
      - 'infrastructure/ansible/**'

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v6
        with:
          path: "infrastructure/ansible"

  ansible-apply:
    needs: ansible-lint
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Install Ansible collections
        run: ansible-galaxy collection install truenas.scale

      - name: Apply Ansible configuration
        env:
          TRUENAS_API_KEY: ${{ secrets.TRUENAS_API_KEY }}
        run: |
          cd infrastructure/ansible
          ansible-playbook playbooks/site.yml
