---
endpoints:
  - name: "${APP}"
    url: "http://${APP}.${GATUS_NAMESPACE:=default}.svc.cluster.local${GATUS_PATH:=/}"
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == ${GATUS_STATUS:=200}"
