---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
configMapGenerator:
  - name: coredns-helm-values
    files:
      - resources/values.yaml
configurations:
  - kustomizeconfig.yaml
